### ISSUE TITLE
usb/insert job get error when no `udisks2`

### ISSUE THREAD

**Issue by LiaoU3** [canonical/checkbox#1029]
### Bug Description

usb/insert related job will get error when there's no package `udisks2`.
I have 2 solutions to this issue.
1. Package `udisks2` into checkbox snap.
2. Add require `package.name == 'udisks2'` and add flag `fail-on-resource`

### To Reproduce

1. Prepare a DUT with image which does not have  `udisks2`.
2. Install checkbox
   1. sudo snap install checkbox22 --beta
   2. sudo snap install checkbox --classic --beta
3. checkbox.checkbox-cli run com.canonical.certification::usb/insert

### Environment

- OS: Ubuntu Desktop
- Checkbox Type: Snap
- Checkbox Version: 3.3.0-dev19
- Hardware: KD240 ([202307-31906](https://certification.canonical.com/hardware/202307-31906/))

### Relevant log output

```shell
ubuntu@kria:~$ checkbox.checkbox-cli run com.canonical.certification::usb/insert
$PROVIDERPATH is defined, so following provider sources are ignored ['/home/ubuntu/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop']
===========================[ Running Selected Jobs ]============================
==============[ Running job 1 / 1. Estimated time left: 0:02:00 ]===============
-----------------[ USB 2.0 storage device insertion detected ]------------------
ID: com.canonical.certification::usb/insert
Category: com.canonical.plainbox::usb
Purpose:

Check system can detect USB 2.0 storage when inserted.
NOTE: Make sure the USB storage device has a partition before starting
the test.

Steps:

1. Press continue
2. Wait until the message "INSERT NOW" is printed on the screen
3. Connect USB 2.0 storage device

Pick an action
    => press ENTER to continue
  c => add a comment
  s => skip this job
  q => save the session and quit
[csq]:
... 8< -------------------------------------------------------------------------


INSERT NOW


Traceback (most recent call last):
  File "/snap/checkbox22/current/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/snap/checkbox22/current/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/snap/checkbox22/current/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.UDisks': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/nest-ohvtylnr.bd8a251854a06645358ed11d5990ff3362645c52e8d4c6ef737bd465e950f526/removable_storage_watcher.py", line 957, in <module>
    sys.exit(main())
  File "/tmp/nest-ohvtylnr.bd8a251854a06645358ed11d5990ff3362645c52e8d4c6ef737bd465e950f526/removable_storage_watcher.py", line 951, in main
    return listener.check(args.timeout)
  File "/tmp/nest-ohvtylnr.bd8a251854a06645358ed11d5990ff3362645c52e8d4c6ef737bd465e950f526/removable_storage_watcher.py", line 105, in check
    self._starting_devices = self.get_existing_devices()
  File "/tmp/nest-ohvtylnr.bd8a251854a06645358ed11d5990ff3362645c52e8d4c6ef737bd465e950f526/removable_storage_watcher.py", line 227, in get_existing_devices
    ud_manager_obj = self._bus.get_object("org.freedesktop.UDisks",
  File "/snap/checkbox22/current/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/snap/checkbox22/current/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/snap/checkbox22/current/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/snap/checkbox22/current/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/snap/checkbox22/current/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks was not provided by any .service files
------------------------------------------------------------------------- >8 ---
Outcome: job failed
Finalizing session that hasn't been submitted anywhere: checkbox-run-2024-02-29T08.51.54
==================================[ Results ]===================================
 ☒ : USB 2.0 storage device insertion detected
```

**Comment by baconYao** [comment]
PR #1130 causes "usb/insert" joba failed on Baoshan G700 with UC22 image

Submission: https://certification.canonical.com/hardware/202308-31931/submission/365351/test-results/fail/?term=usb%2Finsert

I've tried to install `udisks2` snap but failed.

```bash
ceqa@ubuntu:~$ snap info udisks2
name: udisks2
summary: D-Bus service to access and manipulate storage devices
publisher: Canonical✓
store-url: https://snapcraft.io/udisks2
contact: snaps@canonical.com
license: Other Open Source
description: |
  The udisks project provides a daemon, tools and libraries to access
  and manipulate disks and storage devices.

  Please find the source code for this snap at:
  https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/udisks
snap-id: KTyDAsgNZg4u9UBJ63MHn6q12fmUjOfn
channels:
  latest/stable: 2.6.4-2 2017-07-17 (102) 2MB -
  latest/candidate: 2.6.4-2 2017-06-09 (102) 2MB -
  latest/beta: 2.6.4-2 2017-06-07 (102) 2MB -
  latest/edge: 2.6.4-3-dev 2017-06-07 (106) 2MB -

ceqa@ubuntu:~$ sudo snap install udisks2
error: snap "udisks2" is not available on stable but is available to install on
       the following channels:

       candidate snap install --candidate udisks2
       beta snap install --beta udisks2
       edge snap install --edge udisks2

       Please be mindful pre-release channels may include features not
       completely tested or implemented. Get more information with 'snap info
       udisks2'.

ceqa@ubuntu:~$ sudo snap install udisks2 --candidate
error: snap "udisks2" is not available on candidate but is available to install
       on the following channels:

       beta snap install --beta udisks2
       edge snap install --edge udisks2

       Get more information with 'snap info udisks2'.

ceqa@ubuntu:~$ sudo snap install udisks2 --beta
error: snap "udisks2" is not available on beta but is available to install on
       the following channels:

       edge snap install --edge udisks2

       Get more information with 'snap info udisks2'.

ceqa@ubuntu:~$ sudo snap install udisks2 --edge
error: snap "udisks2" is not available on latest/edge but other tracks exist.

       Please be mindful that different tracks may include different features.
       Get more information with 'snap info udisks2'
``` 

**[Additional]**
CID: 202308-31931
SKU: G700
Image: genio-core-22-20240418-101.img
Kernel: 5.15.0-1030-mtk

```bash
ceqa@ubuntu:~$ snap list
Name Version Rev Tracking Publisher Notes
bluez 5.64-5 368 22/stable canonical✓ -
bugit 1.1 24 latest/stable pieq devmode
checkbox-baoshan 0.5dev-jammy 128 latest/edge ce-certification-qa devmode
checkbox-ce-oem 1.0-jammy 203 latest/edge ce-certification-qa devmode
checkbox22 4.0.0-dev226 886 latest/beta ce-certification-qa -
```

**Comment by baconYao** [comment]
Able to install the udisks2 snap via command `$ sudo snap install udisks2 --channel=latest/edge`

Pass the usb jobs, submission: https://certification.canonical.com/hardware/202308-31931/submission/365428/test-results/pass/?term=usb

**Comment by LiaoU3** [comment]
I have veried it is now fixed on the latest checkbox
```
checkbox    4.1.0-dev25    7796   22.04/beta     ce-certification-qa  classic
checkbox22  4.1.0-dev33    1045   latest/edge    ce-certification-qa  -
```
https://certification.canonical.com/hardware/202307-31904/submission/384475/
