### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by plars** [canonical/checkbox#1082]
### Bug Description

Running `checkbox-cli --version` resulted in the following error:
```
Traceback (most recent call last):
  File "/usr/bin/checkbox-cli", line 5, in <module>
    from checkbox_ng.launcher.checkbox_cli import main
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/checkbox_cli.py", line 30, in <module>
    from plainbox.impl.session.assistant import SessionAssistant
  File "/usr/lib/python3/dist-packages/plainbox/impl/session/__init__.py", line 59, in <module>
    from plainbox.impl.session.jobs import InhibitionCause
  File "/usr/lib/python3/dist-packages/plainbox/impl/session/jobs.py", line 38, in <module>
    from plainbox.impl.unit.job import JobDefinition
  File "/usr/lib/python3/dist-packages/plainbox/impl/unit/__init__.py", line 26, in <module>
    from plainbox.impl.secure.plugins import PkgResourcesPlugInCollection
  File "/usr/lib/python3/dist-packages/plainbox/impl/secure/plugins.py", line 50, in <module>
    import pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 85, in <module>
    from pkg_resources.extern import platformdirs
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "/usr/lib/python3/dist-packages/pkg_resources/extern/__init__.py", line 52, in create_module
    return self.load_module(spec.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/extern/__init__.py", line 37, in load_module
    __import__(extant)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/platformdirs/__init__.py", line 16, in <module>
    from .api import PlatformDirsABC
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1069, in get_code
  File "<frozen importlib._bootstrap_external>", line 729, in _compile_bytecode
ValueError: bad marshal data (unknown type code)
```

### To Reproduce

1. sudo add-apt-repository ppa:checkbox-dev/beta -y
2. sudo DEBIAN_FRONTEND=noninteractive apt-get -qq install -o Dpkg::Options::=--force-confdef -y --force-yes checkbox-ng python3-checkbox-ng checkbox-provider-base checkbox-provider-resource checkbox-provider-sru fswebcam obexftp wmctrl iperf mesa-utils vim pastebinit fwts xorg-dev gir1.2-clutter-1.0
3. checkbox-cli --version

### Environment

- Ubuntu 23.10 (amd64)
- checkbox from debs (4.0.0~dev139~ubuntu23.10.1)

**Comment by Hook25** [comment]
This is very weird and I'm unsure this is related to Checkbox actually. [This seems like this error I've encountered before](
https://stackoverflow.com/questions/30861493/how-to-fix-python-valueerrorbad-marshal-data), namely that the `__pycache__` of the module was compiled by an incompatible version of python to the one currently running. Could this be the case? I can't see a way this could happen on noble, yet the stacktrace seems to hint at that.

**Comment by Hook25** [comment]
I am unable to replicate this issue at all. Once cleaned the machine that exposed this initially works as intended. Did you encounter again on some other device since you opened this issue?

**Comment by plars** [comment]
yeah it's strange - I was able to reproduce it at first, but now I'm not able to. Let's close it for now - can always reopen or open a new one if it comes back. Thanks!
