### ISSUE TITLE
`bluetooth4/beacon_eddystone_url_*` failed

### ISSUE THREAD

**Issue by hanhsuan** [canonical/checkbox#1114]
### Bug Description

While executing `bluetooth4/beacon_eddystone_url_*`, the test will fail due to `TypeError: main() missing 1 required positional argument: 'argv'`. This should relate to #1086.

[submission](https://certification.canonical.com/hardware/202401-33397/submission/362062/test/76077/result/40043054/)

### To Reproduce

1. execute `bluetooth4/beacon_eddystone_url_*` test case

### Environment

- OS: jammy
- Checkbox type: debian
- checkbox version: 4.0.0.dev194

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/bin/checkbox-support-eddystone_scanner", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/checkbox_support/helpers/timeout.py", line 69, in _f
    return run_with_timeout(f, timeout_s, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/checkbox_support/helpers/timeout.py", line 56, in run_with_timeout
    raise exception_queue.get()
  File "/usr/lib/python3/dist-packages/checkbox_support/helpers/timeout.py", line 43, in _f
    result_queue.put(f(*args, **kwargs))
TypeError: main() missing 1 required positional argument: 'argv'
```

**Comment by Hook25** [comment]
thank you for the report, I know what is the cause and I will fix it as soon as possible
