### ISSUE TITLE
LP1877178: cannot connect to BT 4.0 devices on 20.04

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#112]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1877178

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-05-06 20:16:06	| 6	| Medium	| False  	|

## Description
[Summary]
cannot connect to BT 4.0 devices by checkbox, but GUI can

[Steps to reproduce]
1. Run bluetooth4/HOGP-mouse or bluetooth4/HOGP-keyboard

[Expected result]
Can connect to BT 4.0 devices normally

[Actual result]
Error msg shown:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/checkbox_support/bt_helper.py", line 159, in _scan_timeout
    dbus.Interface(adapter, ADAPTER_IFACE).StopDiscovery()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.bluez.Error.InProgress: Operation already in progress

[Failure rate]
SRV5-DVT1-C3: 10/10

[Additional information]
SKU: SRV5-DVT1-C3, SRV5-DVT1-C4
Manifest: canonical-oem-somerville-focal-amd64-20200502-85+fossa-bulbasaur+X21
system-manufacturer: Dell Inc.
system-product-name: Vostro 5301
bios-version: 0.1.12
CPU: Genuine Intel(R) CPU 0000 @ 2.30GHz (8x)
GPU: 0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:9a49]
kernel-version: 5.6.0-1008-oem

## Attachments
[checkbox-session.tgz](https://api.launchpad.net/devel/bugs/1877178/+attachment/5367496/data)
[snap_list.log](https://api.launchpad.net/devel/bugs/1877178/+attachment/5367497/data)
[acpidump.log](https://api.launchpad.net/devel/bugs/1877178/+attachment/5367498/data)
[sosreport-V5-C3-20200506161620.tar.gz](https://api.launchpad.net/devel/bugs/1877178/+attachment/5367499/data)

Tags:
['ce-qa-concern', 'hwe-bluetooth']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~huntu207 wrote on 2020-05-06 20:17:53:
Automatically attached

##### https://launchpad.net/~huntu207 wrote on 2020-05-06 20:17:55:
Automatically attached

##### https://launchpad.net/~huntu207 wrote on 2020-05-06 20:18:05:
Automatically attached

##### https://launchpad.net/~huntu207 wrote on 2020-05-06 20:18:29:
Automatically attached
