### ISSUE TITLE
PermissionError with checkbox 24 on arm64

### ISSUE THREAD

**Issue by LiaoU3** [canonical/checkbox#1225]
### Bug Description

After installing checkbox (24.04/edge) and checkbox24 (edge) and run checkbox-cli, we get `PermissionError`. BTW, I did not observe this issue on amd64.

snap list
```
checkbox      4.0.0-dev250   6643   24.04/edge     ce-certification-qa  -
checkbox24    4.0.0-dev256   9      latest/edge    ce-certification-qa  -
```

### To Reproduce

1. sudo snap install checkbox24 --edge
2. sudo snap install checkbox --channel 24.04/edge --classic
3. checkbox.checkbox-cli

### Environment

 - OS: classic
 - Checkbox: snap
 - Hardware
    - Genio 1200 EVK ([202404-33953](https://certification.canonical.com/hardware/202404-33953/))
    - CRD8380X DVT1.0_4th ([202311-32348](https://certification.canonical.com/hardware/202311-32348/))

### Relevant log output

```shell
ubuntu@mtk-genio:~$ checkbox.checkbox-cli 
/snap/checkbox/6643/checkbox-runtime/wrapper_common: line 40: /usr/bin/findmnt: Permission denied
/snap/checkbox/6643/checkbox-runtime/wrapper_common: line 40: /usr/bin/findmnt: Permission denied
Preparing...
ERROR:plainbox.bug:Undeclared exception PermissionError raised from start_new_session
Traceback (most recent call last):
  File "/snap/checkbox/6643/checkbox-runtime/bin/checkbox-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/snap/checkbox/6643/checkbox-runtime/lib/python3.12/site-packages/checkbox_ng/launcher/checkbox_cli.py", line 166, in main
    return subcmd.invoked(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "/snap/checkbox/6643/checkbox-runtime/lib/python3.12/site-packages/checkbox_ng/launcher/subcommands.py", line 262, in invoked
    self._start_new_session()
  File "/snap/checkbox/6643/checkbox-runtime/lib/python3.12/site-packages/checkbox_ng/launcher/subcommands.py", line 619, in _start_new_session
    self.ctx.sa.start_new_session(title, UnifiedRunner, runner_kwargs)
  File "/snap/checkbox/6643/checkbox-runtime/lib/python3.12/site-packages/plainbox/impl/decorators.py", line 153, in wrapper
    raise exc
  File "/snap/checkbox/6643/checkbox-runtime/lib/python3.12/site-packages/plainbox/impl/decorators.py", line 145, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/snap/checkbox/6643/checkbox-runtime/lib/python3.12/site-packages/plainbox/impl/session/assistant.py", line 494, in start_new_session
    self._manager = SessionManager.create(prefix=title + "-")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/checkbox/6643/checkbox-runtime/lib/python3.12/site-packages/plainbox/impl/session/manager.py", line 180, in create
    storage = SessionStorage.create(prefix)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/checkbox/6643/checkbox-runtime/lib/python3.12/site-packages/plainbox/impl/session/storage.py", line 233, in create
    WellKnownDirsHelper.populate_base()
  File "/snap/checkbox/6643/checkbox-runtime/lib/python3.12/site-packages/plainbox/impl/session/storage.py", line 64, in populate_base
    os.makedirs(dirname)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/var/tmp/checkbox-ng/sessions'
```

**Comment by Hook25** [comment]
Oh wow, I think I pushed the wrong snap for arm64 for core24. Let me confirm that and push a fix

**Comment by Hook25** [comment]
I have checked this on noble and it now works. Thank you for the report
```
ubuntu@ubuntu:~$ checkbox.checkbox-cli --version
$PROVIDERPATH is defined, so following provider sources are ignored ['/home/ubuntu/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
4.0.0.dev256
ubuntu@ubuntu:~$ snap list
Name        Version       Rev    Tracking       Publisher            Notes
checkbox    4.0.0-dev264  6878   24.04/edge     ce-certification-qa  classic
checkbox24  4.0.0-dev256  9      latest/edge    ce-certification-qa  -
core24      20240426      410    latest/stable  canonical✓           base
snapd       2.62          21467  latest/stable  canonical✓           snapd
```

**Comment by Hook25** [comment]
I will close this as fixed, feel free to reopen it you encounter this again
