### ISSUE TITLE
.*auto_switch_card.* is causing problem on desktop/workstation

### ISSUE THREAD

**Issue by kevinyehk** [canonical/checkbox#1336]
### Bug Description

This issue is for desktop/workstation that have more than 2 graphic card and test with 20.04.
For some of desktop/workstation machines, the default video output port has been decided in BIOS setting, if the default output is set to dGPU, when we run `prime-select intel`, next boot the iGPU driver won't be loaded, for the default output is set to iGPU, we can't run `prime-select nvidia`.

And for the machines that have 2 dGPU and use NVLink, checkbox still treats them as having a dGPU and an iGPU and executes `prime-select intel` to switch the card.

As I described above, could we consider removing the .*auto_switch_card.*  test case on desktop/workstation for automated test plan? Since we still need to test 20.04 for many years, and we don't want to exclude the test case from jenkins job side.
 

### To Reproduce

1. Find a desktop has dGPU and the default video output in the BIOS is iGPU or dGPU only.
2. Run the automated graphics test plan.
3. After switching the profile, you will see the machine can't have the graphic session in next boot.

### Environment

- OS : ubuntu 20.04 desktop
- Checkbox type: debian
- Checkbox version: I think it's across all version

### Relevant log output

```shell
---------------------------[ Running job 127 / 185 ]----------------------------
[ Switch GPU to Advanced Micro Devices, Inc. [AMD/ATI] PCI ID 0x1638 and reboot ]
ID: com.canonical.certification::graphics/2_auto_switch_card_PCI_ID_0x1638
Category: Graphics tests
--------------------------------------------------------------------------------
DEBUG    Invoking username: ubuntu
DEBUG    Arguments: Namespace(append=False, check_hardware_list=False, checkbox_respawn_cmd='/var/tmp/checkbox-ng/sessions/session_title-2024-07-10T12.35.52.session/session-share/__respawn_checkbox', fwts=False, hardware_delay=30, log_dir='/var/tmp/checkbox-ng/sessions/session_title-2024-07-10T12.35.52.session/session-share', log_filename='/var/tmp/checkbox-ng/sessions/session_title-2024-07-10T12.35.52.session/session-share/pm_test.reboot.1.log', log_level=10, log_level_str='debug', max_pm_time=300, min_pm_time=0, pm_delay=5, pm_operation='reboot', pm_timestamp=0, repetitions=1, silent=True, start=1720615791, suspends_before_reboot=0, total=1, wakeup=0)
DEBUG    Extra Arguments: []
DEBUG    Enabling autologin for this user...
DEBUG    Enabling user to execute test as root...
DEBUG    Executing: "sed -i -e '$a# Automatically added by pm.py\\nubuntu ALL=NOPASSWD: /usr/bin/python3' /etc/sudoers"...
DEBUG    Writing desktop file ('/home/ubuntu/.config/autostart/pm_test.py.desktop')...
DEBUG    
[Desktop Entry]
Name=reboot test
Comment=Verify reboot works properly
Exec=sudo /usr/bin/python3 /usr/lib/checkbox-provider-base/bin/pm_test.py -r 0 -w 0 --hardware-delay 30 --pm-delay 5 --min-pm-time 0 --max-pm-time 300 --append --total 1 --start 1720615791 --pm-timestamp 1720615791 --silent --log-level=debug --log-dir=/var/tmp/checkbox-ng/sessions/session_title-2024-07-10T12.35.52.session/session-share --suspends-before-reboot=0 --checkbox-respawn-cmd=/var/tmp/checkbox-ng/sessions/session_title-2024-07-10T12.35.52.session/session-share/__respawn_checkbox   reboot
Type=Application
X-GNOME-Autostart-enabled=true
Hidden=false

INFO     reboot operations remaining: 1
INFO     Gathering hardware information...
DEBUG    Executing: 'lspci | grep Network'...
DEBUG    Output:
- returncode:
0
- stdout:
05:00.0 Network controller: Intel Corporation Wi-Fi 6 AX200 (rev 1a)

DEBUG    Executing: 'lspci | grep Ethernet'...
DEBUG    Output:
- returncode:
0
- stdout:
04:00.1 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 29)

DEBUG    Executing: "ifconfig -a | grep -A1 '^\\w'"...
DEBUG    Output:
- returncode:
0
- stdout:
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.102.162.161  netmask 255.255.252.0  broadcast 10.102.163.255
--
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
--
wlp5s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether e0:d4:64:c5:31:fe  txqueuelen 1000  (Ethernet)

DEBUG    Executing: "iwconfig | grep -A1 '^\\w'"...
DEBUG    Output:
- returncode:
0
- stdout:
wlp5s0    IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=22 dBm   

- stderr:
lo        no wireless extensions.

eno1      no wireless extensions.


DEBUG    Networking:
05:00.0 Network controller: Intel Corporation Wi-Fi 6 AX200 (rev 1a)

04:00.1 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 29)

eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.102.162.161  netmask 255.255.252.0  broadcast 10.102.163.255
--
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
--
wlp5s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether e0:d4:64:c5:31:fe  txqueuelen 1000  (Ethernet)

wlp5s0    IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=22 dBm   

DEBUG    Executing: "hciconfig -a | grep -A2 '^\\w'"...
DEBUG    Output:
- returncode:
0
- stdout:
hci0:	Type: Primary  Bus: USB
	BD Address: E0:D4:64:C5:32:02  ACL MTU: 1021:4  SCO MTU: 96:6
	UP RUNNING 

DEBUG    Bluetooth Device:
hci0:	Type: Primary  Bus: USB
	BD Address: E0:D4:64:C5:32:02  ACL MTU: 1021:4  SCO MTU: 96:6
	UP RUNNING 

DEBUG    Executing: 'lspci | grep VGA'...
DEBUG    Output:
- returncode:
0
- stdout:
01:00.0 VGA compatible controller: NVIDIA Corporation GP107GL [Quadro P400] (rev a1)
06:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 1638 (rev d9)

DEBUG    Video Card:
01:00.0 VGA compatible controller: NVIDIA Corporation GP107GL [Quadro P400] (rev a1)
06:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 1638 (rev d9)

DEBUG    Executing: 'xinput list --name-only | sort'...
DEBUG    Output:
- returncode:
0
- stdout:
HP WMI hotkeys
Power Button
Power Button
Video Bus
Virtual core keyboard
Virtual core pointer
Virtual core XTEST keyboard
Virtual core XTEST pointer

DEBUG    Touchpad and Keyboard:
HP WMI hotkeys
Power Button
Power Button
Video Bus
Virtual core keyboard
Virtual core pointer
Virtual core XTEST keyboard
Virtual core XTEST pointer

DEBUG    Executing: 'pactl list | grep Sink'...
DEBUG    Output:
- returncode:
1
- stderr:
XDG_RUNTIME_DIR (/run/user/1001) is not owned by us (uid 0), but by uid 1001! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
Connection failure: Connection refused
pa_context_connect() failed: Connection refused

DEBUG    Pulse Audio Sink:
b''
DEBUG    Executing: 'pactl list | grep Source'...
DEBUG    Output:
- returncode:
1
- stderr:
XDG_RUNTIME_DIR (/run/user/1001) is not owned by us (uid 0), but by uid 1001! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
Connection failure: Connection refused
pa_context_connect() failed: Connection refused

DEBUG    Pulse Audio Source:
b''
DEBUG    Executing: 'fwts -r stdout klog oops'...
DEBUG    Output:
- returncode:
0
- stdout:
Running 2 tests, results appended to stdout.log
Results generated by fwts: Version V24.03.00 (2024-04-08 03:21:26).

Some of this work - Copyright (c) 1999 - 2023, Intel Corp. All rights reserved.
Some of this work - Copyright (c) 2010 - 2023, Canonical.
Some of this work - Copyright (c) 2016 - 2023, IBM.
Some of this work - Copyright (c) 2017 - 2023, ARM Ltd.

This test run on 10/07/24 at 20:49:51 on host Linux
hp-elitedesk-805-g8-small-form-factor-pc-c28938 5.15.0-116-generic
#126~20.04.1-Ubuntu SMP Mon Jul 1 15:40:07 UTC 2024 x86_64.

Command: "fwts -r stdout klog oops".
Running tests: klog oops.

klog: Scan kernel log for errors and warnings.
--------------------------------------------------------------------------------
Test 1 of 1: Kernel log error check.
PASSED: Test 1, Found no errors in kernel log.

================================================================================
1 passed, 0 failed, 0 warning, 0 aborted, 0 skipped, 0 info only.
================================================================================

oops: Scan kernel log for Oopses.
--------------------------------------------------------------------------------
Test 1 of 1: Kernel log oops check.
PASSED: Test 1, Found no oopses in kernel log.
PASSED: Test 1, Found no WARN_ON warnings in kernel log.

================================================================================
2 passed, 0 failed, 0 warning, 0 aborted, 0 skipped, 0 info only.
================================================================================


3 passed, 0 failed, 0 warning, 0 aborted, 0 skipped, 0 info only.

Test Failure Summary
================================================================================

Critical failures: NONE

High failures: NONE

Medium failures: NONE

Low failures: NONE

Other failures: NONE

Test           |Pass |Fail |Abort|Warn |Skip |Info |
---------------+-----+-----+-----+-----+-----+-----+
klog           |    1|     |     |     |     |     |
oops           |    2|     |     |     |     |     |
---------------+-----+-----+-----+-----+-----+-----+
Total:         |    3|    0|    0|    0|    0|    0|
---------------+-----+-----+-----+-----+-----+-----+

- stderr:
Test: Scan kernel log for errors and warnings.                              
                                                                     :   0.0% /
el log error check.                                            :   0.0% -
el log error check.                                            :   0.0% \
el log error check.                                            :   7.5% |
el log error check.                                            :  15.0% /
el log error check.                                            :  23.0% -
el log error check.                                            :   0.0% \
el log error check.                                            :  12.0% |
el log error check.                                            :  24.0% /
el log error check.                                            :  50.0% -
el log error check.                                            :  50.0% \
                                                                         
el log error check.                                 1 passed
Test: Scan kernel log for Oopses.                                           
                                                                     :  50.0% |
el log oops check.                                             :  50.0% /
el log oops check.                                             : 100.0% -
                                                                         
el log oops check.                                  2 passed

INFO     Gathering system information...
XDG_RUNTIME_DIR (/run/user/1001) is not owned by us (uid 0), but by uid 1001! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)

(pm_test.py:8892): Gtk-CRITICAL **: 20:49:57.330: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed
INFO     Executing new 'reboot' operation...
DEBUG    Executing: 'sleep 5; reboot'...
Connection lost!
connection closed by peer
Reconnecting -\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/...
Reconnected (took: 91s)
[ Switch GPU to Advanced Micro Devices, Inc. [AMD/ATI] PCI ID 0x1638 and reboot ]
ID: com.canonical.certification::graphics/2_auto_switch_card_PCI_ID_0x1638
Category: Graphics tests
--------------------------------------------------------------------------------
Outcome: job passed
---------------------------[ Running job 138 / 195 ]----------------------------
-----[ Switch GPU to NVIDIA Corporation GP107GL [Quadro P400] and reboot ]------
ID: com.canonical.certification::graphics/1_auto_switch_card_GP107GL__Quadro_P400_
Category: Graphics tests
--------------------------------------------------------------------------------
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
DEBUG    Invoking username: ubuntu
DEBUG    Arguments: Namespace(append=False, check_hardware_list=False, checkbox_respawn_cmd='/var/tmp/checkbox-ng/sessions/session_title-2024-07-10T12.35.52.session/session-share/__respawn_checkbox', fwts=False, hardware_delay=30, log_dir='/var/tmp/checkbox-ng/sessions/session_title-2024-07-10T12.35.52.session/session-share', log_filename='/var/tmp/checkbox-ng/sessions/session_title-2024-07-10T12.35.52.session/session-share/pm_test.reboot.1.log', log_level=10, log_level_str='debug', max_pm_time=300, min_pm_time=0, pm_delay=5, pm_operation='reboot', pm_timestamp=0, repetitions=1, silent=True, start=1720615904, suspends_before_reboot=0, total=1, wakeup=0)
DEBUG    Extra Arguments: []
DEBUG    Enabling autologin for this user...
DEBUG    Enabling user to execute test as root...
DEBUG    Executing: "sed -i -e '$a# Automatically added by pm.py\\nubuntu ALL=NOPASSWD: /usr/bin/python3' /etc/sudoers"...
DEBUG    Writing desktop file ('/home/ubuntu/.config/autostart/pm_test.py.desktop')...
DEBUG    
[Desktop Entry]
Name=reboot test
Comment=Verify reboot works properly
Exec=sudo /usr/bin/python3 /usr/lib/checkbox-provider-base/bin/pm_test.py -r 0 -w 0 --hardware-delay 30 --pm-delay 5 --min-pm-time 0 --max-pm-time 300 --append --total 1 --start 1720615904 --pm-timestamp 1720615904 --silent --log-level=debug --log-dir=/var/tmp/checkbox-ng/sessions/session_title-2024-07-10T12.35.52.session/session-share --suspends-before-reboot=0 --checkbox-respawn-cmd=/var/tmp/checkbox-ng/sessions/session_title-2024-07-10T12.35.52.session/session-share/__respawn_checkbox   reboot
Type=Application
X-GNOME-Autostart-enabled=true
Hidden=false

INFO     reboot operations remaining: 1
/tmp/nest-3nwt_jgb.70efa4d2958f71c1c6a87887ba96432777ba411525388b76ae93766dbd63b437/pm_test.py:163: PyGTKDeprecationWarning: The "buttons" argument must be a Gtk.ButtonsType enum value. Please use the "add_buttons" method for adding buttons. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  CountdownDialog(
Traceback (most recent call last):
  File "/tmp/nest-3nwt_jgb.70efa4d2958f71c1c6a87887ba96432777ba411525388b76ae93766dbd63b437/pm_test.py", line 1230, in <module>
    sys.exit(main())
  File "/tmp/nest-3nwt_jgb.70efa4d2958f71c1c6a87887ba96432777ba411525388b76ae93766dbd63b437/pm_test.py", line 63, in main
    operation.run()
  File "/tmp/nest-3nwt_jgb.70efa4d2958f71c1c6a87887ba96432777ba411525388b76ae93766dbd63b437/pm_test.py", line 151, in run
    self.run_pm_command()
  File "/tmp/nest-3nwt_jgb.70efa4d2958f71c1c6a87887ba96432777ba411525388b76ae93766dbd63b437/pm_test.py", line 163, in run_pm_command
    CountdownDialog(
  File "/tmp/nest-3nwt_jgb.70efa4d2958f71c1c6a87887ba96432777ba411525388b76ae93766dbd63b437/pm_test.py", line 562, in __init__
    super(CountdownDialog, self).__init__(title=title, buttons=buttons)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 577, in __init__
    self._init(*args, **new_kwargs)
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 319, in new_init
    return super_init_func(self, **new_kwargs)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 520, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.

ERROR: Output timeout reached! (3600s)
```

**Comment by fernando79513** [comment]
Hey, Kevin! TYVM for the investigation on the issue, it was really helpful

I am not sure about removing the test from the automated test plan is the best approach.
Since we are defining how these tests are running in the graphics_card_resource script, I am wondering if we could the information we need to skip this test or run it properly on the devices that are failing to run this test.

Apart from [202004-27850](https://certification.canonical.com/hardware/202004-27850/), have we identified more devices that are failing this test because of this reason?

**Comment by kevinyehk** [comment]
@fernando79513 [202204-30169](https://certification.canonical.com/hardware/202204-30169/) also has 2 NV GPU with NVLink.

Yeah, I agree with you that removing the test from the test plan is not the best way, but adding some requirement, such as running the test only on desktop and workstation seems doable.
For example, `dmi.product in ['Notebook','Laptop','Portable','All In One','All-In-One','AIO','Convertible']`
