### ISSUE TITLE
fwts update broke miscellanea/dkms_build_validation test

### ISSUE THREAD

**Issue by jocave** [canonical/checkbox#1383]
### Bug Description

Test definition: https://github.com/canonical/checkbox/blob/main/providers/sru/units/sru.pxu#L7

After opening a bug in fwts to understand signifcant number of failures we are now seeing on certain kernel types the maintain says the behaviour of the dkms module is as designed implying that we need to handle this new status in this job:

https://bugs.launchpad.net/fwts/+bug/2075481

### To Reproduce

Run the com.canonical.certification::sru test plan on a kernel such as linux-hwe-6.8

### Environment

- Ubuntu Desktop 22.04
- Checkbox from snap (beta)

### Relevant log output

```shell
Traceback (most recent call last):
File "/tmp/nest-2fo82grw.ae4fce10be9a3460f6e810600e3f80634610fb0f0050368572bc33afc4bd78bf/dkms_build_validation.py", line 186, in <module>
sys.exit(main())
File "/tmp/nest-2fo82grw.ae4fce10be9a3460f6e810600e3f80634610fb0f0050368572bc33afc4bd78bf/dkms_build_validation.py", line 168, in main
sorted_kernel_info = parse_dkms_status(dkms_status, ubuntu_release)
File "/tmp/nest-2fo82grw.ae4fce10be9a3460f6e810600e3f80634610fb0f0050368572bc33afc4bd78bf/dkms_build_validation.py", line 67, in parse_dkms_status
kernel_ver = details.split(", ")[1]
IndexError: list index out of range
```

**Comment by boukeas** [comment]
I have re-opened the bug after [this failure](https://certification.canonical.com/hardware/202208-30512/submission/394740/test-results/fail/) on `6.8.0-44.44~22.04.1`. According to this [MM discussion](https://chat.canonical.com/canonical/pl/7my9dwyndtfb8gw1fb7fio4hsy):
> the dkms module won't be built when the kernel with efi_test driver which is 6.8, but last time when we test -40 kernel, the dkms status command still listed the status as added, so Jocave created a [PR](https://github.com/canonical/checkbox/pull/1426) for this, but now with -44 kenrel, the dkms status seems not to list the module won't be built. We need another fix for this test.
