### ISSUE TITLE
Various *-detect jobs failing on certain devices due to udevadm parser problem

### ISSUE THREAD

**Issue by omar-selo** [canonical/checkbox#1407]
### Bug Description

From SRU testing, there has been a few environments failing `usb/storage-detect` even though they have a usb stick connected already, with the following error log:

```
     Traceback (most recent call last):
  File "/tmp/nest-_o6psind.5898582bde834e198d8c971d79f8e1aa6851b304be424661f5e7be4c435e3acd/udev_resource.py", line 198, in <module>
    main()
  File "/tmp/nest-_o6psind.5898582bde834e198d8c971d79f8e1aa6851b304be424661f5e7be4c435e3acd/udev_resource.py", line 191, in main
    if filter_by_categories(udev, args.filter) == 0:
  File "/tmp/nest-_o6psind.5898582bde834e198d8c971d79f8e1aa6851b304be424661f5e7be4c435e3acd/udev_resource.py", line 84, in filter_by_categories
    for device in udev.run():
  File "/usr/lib/python3/dist-packages/checkbox_support/parsers/udevadm.py", line 1521, in run
    for parent in (device._stack[-1], device._stack[-2]):
IndexError: list index out of range
```

### To Reproduce

Run the following SRU job http://10.102.156.15:8080/job/cert-oem-sru-jammy-desktop-hp-elitebook-835-13-inch-g10-notebook-pc-c31696/

### Environment

See submission of the above mentioned job https://certification.canonical.com/hardware/202306-31696/submission/384989/

### Additional context

[MM conversation](https://chat.canonical.com/canonical/pl/ii543ojm47rbxre3594nzi93ih)

**Comment by jocave** [comment]
On machines that exhibit this failure many jobs my fail as it is common for detect jobs to rely on the udevadm parser

https://certification.canonical.com/hardware/202306-31695/submission/385992/test-results/fail/
