### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'Get' in wwan_tests.py

### ISSUE THREAD

**Issue by pieqq** [canonical/checkbox#1411]
### Bug Description

We recently hit a problem when running the job `wwan/check-sim-present-.*-auto` on a device in our Cert lab.

See below for output.

### To Reproduce

1. Launch Checkbox
2. Select a test plan with the WWAN category
3. Run the `wwan/check-sim-present-.*-auto` job

### Environment

- [Checkbox Submission](https://certification.canonical.com/hardware/202403-33827/submission/385785/)

### Relevant log output

```shell
Test fails with following output:


Traceback (most recent call last):
  File "/tmp/nest-pl2m78jk.c9755cd73888c12a9df9a44088be9f631e1b25d055103b2e15db38b5980a4870/wwan_tests.py", line 548, in <module>
    WWANTests().main()
  File "/tmp/nest-pl2m78jk.c9755cd73888c12a9df9a44088be9f631e1b25d055103b2e15db38b5980a4870/wwan_tests.py", line 544, in main
    sub_commands[args.subcommand]().invoked()
  File "/tmp/nest-pl2m78jk.c9755cd73888c12a9df9a44088be9f631e1b25d055103b2e15db38b5980a4870/wwan_tests.py", line 499, in invoked
    if not mm.sim_present(mm_id):
  File "/tmp/nest-pl2m78jk.c9755cd73888c12a9df9a44088be9f631e1b25d055103b2e15db38b5980a4870/wwan_tests.py", line 129, in sim_present
    if pi.Get(DBUS_MM1_IF_MODEM, "Sim") != "/":
AttributeError: 'NoneType' object has no attribute 'Get'
```
```


### Additional context

_No response_

**Comment by stanley31huang** [comment]
The LTE modem is not enabled by default, so we have a bootstrapped job to bring it up in the beginning. So the `wwan/check-sim-present-.*-auto` job failed at first round due to no SIM card. And the reason why it failed at second round is there's a reboot job during the testing.

IMHO, the solution would be either we raise an `Exception` in the [MMDbus.__init__ function](https://github.com/canonical/checkbox/blob/main/providers/base/bin/wwan_tests.py#L79) or we make sure the `mm_id` is valid.
