### ISSUE TITLE
Checkbox fails to generate the report with error `Problem with a '2_html_file'`

### ISSUE THREAD

**Issue by kevinyehk** [canonical/checkbox#1470]
### Bug Description

In [this](http://10.102.156.15:8080/job/cert-cc-lab-manager/1496/console) test run for sugarland project, when checkbox tried to generate the test report, it showed up some traceback messages. 

### To Reproduce

1. Run [this](http://10.102.156.15:8080/job/cert-sugarland-pdk-hbt-imx-kernel-latest-beta) snap-testing job

### Environment

- OS : UC20
- Checkbox type: snap
- Checkbox version: 4.1.0-dev25

### Relevant log output

```shell
14:27:46 Problem with a '2_html_file' report using 'com.canonical.plainbox::html' exporter sent to '/home/ubuntu/.local/share/checkbox-ng/submission_2024-09-13T06.27.31.912411.html' transport. Reason Expecting value: line 1 column 1 (char 0)
14:27:46 
14:27:46 ========= Remote Traceback (1) =========
14:27:46 Traceback (most recent call last):
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/lib/python3.8/site-packages/plainbox/vendor/rpyc/core/protocol.py", line 359, in _dispatch_request
14:27:46     res = self._HANDLERS[handler](self, *args)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/lib/python3.8/site-packages/plainbox/vendor/rpyc/core/protocol.py", line 837, in _handle_call
14:27:46     return obj(*args, **dict(kwargs))
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/lib/python3.8/site-packages/plainbox/impl/session/remote_assistant.py", line 847, in exposed_cache_report
14:27:46     exporter.dump_from_session_manager(self._sa._manager, exported_stream)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/lib/python3.8/site-packages/plainbox/impl/exporter/jinja2.py", line 205, in dump_from_session_manager
14:27:46     self.dump(data, stream)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/lib/python3.8/site-packages/plainbox/impl/exporter/jinja2.py", line 175, in dump
14:27:46     self.template.stream(data).dump(stream, encoding="utf-8")
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3/dist-packages/jinja2/environment.py", line 1227, in dump
14:27:46     fp.writelines(iterable)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3.8/tempfile.py", line 917, in writelines
14:27:46     rv = file.writelines(iterable)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3/dist-packages/jinja2/environment.py", line 1223, in <genexpr>
14:27:46     iterable = (x.encode(encoding, errors) for x in self)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3/dist-packages/jinja2/environment.py", line 1271, in __next__
14:27:46     return self._next()
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3/dist-packages/jinja2/environment.py", line 1045, in generate
14:27:46     yield self.environment.handle_exception(exc_info, True)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
14:27:46     reraise(exc_type, exc_value, tb)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
14:27:46     raise value.with_traceback(tb)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/lib/python3.8/site-packages/plainbox/impl/providers/exporters/data/checkbox.html", line 47, in <module>
14:27:46     {%- set system_info = system_info_json|json_load_ordered_dict %}
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/lib/python3.8/site-packages/plainbox/impl/exporter/jinja2.py", line 76, in json_load_ordered_dict
14:27:46     return json.loads(text, object_pairs_hook=OrderedDict)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3.8/json/__init__.py", line 370, in loads
14:27:46     return cls(**kw).decode(s)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3.8/json/decoder.py", line 337, in decode
14:27:46     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
14:27:46     raise JSONDecodeError("Expecting value", s, err.value) from None
14:27:46 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
14:27:46 
14:27:46 Traceback (most recent call last):
14:27:46   File "/usr/local/lib/python3.8/dist-packages/checkbox_ng-0.0.0-py3.8.egg/checkbox_ng/launcher/stages.py", line 666, in _export_results
14:27:46     result = self._export_fn(exporter_id, transport)
14:27:46   File "/usr/local/lib/python3.8/dist-packages/checkbox_ng-0.0.0-py3.8.egg/checkbox_ng/launcher/controller.py", line 829, in local_export
14:27:46     rf = self.sa.cache_report(exporter_id, options)
14:27:46   File "/usr/local/lib/python3.8/dist-packages/checkbox_ng-0.0.0-py3.8.egg/plainbox/vendor/rpyc/core/netref.py", line 240, in __call__
14:27:46     return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
14:27:46   File "/usr/local/lib/python3.8/dist-packages/checkbox_ng-0.0.0-py3.8.egg/plainbox/vendor/rpyc/core/netref.py", line 63, in syncreq
14:27:46     return conn.sync_request(handler, proxy, *args)
14:27:46   File "/usr/local/lib/python3.8/dist-packages/checkbox_ng-0.0.0-py3.8.egg/plainbox/vendor/rpyc/core/protocol.py", line 718, in sync_request
14:27:46     return _async_res.value
14:27:46   File "/usr/local/lib/python3.8/dist-packages/checkbox_ng-0.0.0-py3.8.egg/plainbox/vendor/rpyc/core/async_.py", line 108, in value
14:27:46     raise self._obj
14:27:46 plainbox.vendor.rpyc.core.vinegar/json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
14:27:46 
14:27:46 ========= Remote Traceback (1) =========
14:27:46 Traceback (most recent call last):
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/lib/python3.8/site-packages/plainbox/vendor/rpyc/core/protocol.py", line 359, in _dispatch_request
14:27:46     res = self._HANDLERS[handler](self, *args)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/lib/python3.8/site-packages/plainbox/vendor/rpyc/core/protocol.py", line 837, in _handle_call
14:27:46     return obj(*args, **dict(kwargs))
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/lib/python3.8/site-packages/plainbox/impl/session/remote_assistant.py", line 847, in exposed_cache_report
14:27:46     exporter.dump_from_session_manager(self._sa._manager, exported_stream)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/lib/python3.8/site-packages/plainbox/impl/exporter/jinja2.py", line 205, in dump_from_session_manager
14:27:46     self.dump(data, stream)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/lib/python3.8/site-packages/plainbox/impl/exporter/jinja2.py", line 175, in dump
14:27:46     self.template.stream(data).dump(stream, encoding="utf-8")
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3/dist-packages/jinja2/environment.py", line 1227, in dump
14:27:46     fp.writelines(iterable)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3.8/tempfile.py", line 917, in writelines
14:27:46     rv = file.writelines(iterable)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3/dist-packages/jinja2/environment.py", line 1223, in <genexpr>
14:27:46     iterable = (x.encode(encoding, errors) for x in self)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3/dist-packages/jinja2/environment.py", line 1271, in __next__
14:27:46     return self._next()
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3/dist-packages/jinja2/environment.py", line 1045, in generate
14:27:46     yield self.environment.handle_exception(exc_info, True)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
14:27:46     reraise(exc_type, exc_value, tb)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
14:27:46     raise value.with_traceback(tb)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/lib/python3.8/site-packages/plainbox/impl/providers/exporters/data/checkbox.html", line 47, in <module>
14:27:46     {%- set system_info = system_info_json|json_load_ordered_dict %}
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/lib/python3.8/site-packages/plainbox/impl/exporter/jinja2.py", line 76, in json_load_ordered_dict
14:27:46     return json.loads(text, object_pairs_hook=OrderedDict)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3.8/json/__init__.py", line 370, in loads
14:27:46     return cls(**kw).decode(s)
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3.8/json/decoder.py", line 337, in decode
14:27:46     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
14:27:46   File "/snap/checkbox-shiner/326/checkbox-runtime/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
14:27:46     raise JSONDecodeError("Expecting value", s, err.value) from None
14:27:46 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
14:27:46 
14:27:46 
14:27:46 During handling of the above exception, another exception occurred:
14:27:46 
14:27:46 Traceback (most recent call last):
14:27:46   File "/usr/local/bin/checkbox-cli", line 11, in <module>
14:27:46     load_entry_point('checkbox-ng==0.0.0', 'console_scripts', 'checkbox-cli')()
14:27:46   File "/usr/local/lib/python3.8/dist-packages/checkbox_ng-0.0.0-py3.8.egg/checkbox_ng/launcher/checkbox_cli.py", line 166, in main
14:27:46     return subcmd.invoked(ctx)
14:27:46   File "/usr/local/lib/python3.8/dist-packages/checkbox_ng-0.0.0-py3.8.egg/checkbox_ng/launcher/controller.py", line 175, in invoked
14:27:46     return self.connect_and_run(ctx.args.host, port)
14:27:46   File "/usr/local/lib/python3.8/dist-packages/checkbox_ng-0.0.0-py3.8.egg/checkbox_ng/launcher/controller.py", line 303, in connect_and_run
14:27:46     keep_running = {
14:27:46   File "/usr/local/lib/python3.8/dist-packages/checkbox_ng-0.0.0-py3.8.egg/checkbox_ng/launcher/controller.py", line 776, in run_jobs
14:27:46     self.finish_session()
14:27:46   File "/usr/local/lib/python3.8/dist-packages/checkbox_ng-0.0.0-py3.8.egg/checkbox_ng/launcher/controller.py", line 702, in finish_session
14:27:46     self._export_results()
14:27:46   File "/usr/local/lib/python3.8/dist-packages/checkbox_ng-0.0.0-py3.8.egg/checkbox_ng/launcher/stages.py", line 723, in _export_results
14:27:46     traceback.print_tb(exc)
14:27:46   File "/usr/lib/python3.8/traceback.py", line 53, in print_tb
14:27:46     print_list(extract_tb(tb, limit=limit), file=file)
14:27:46   File "/usr/lib/python3.8/traceback.py", line 72, in extract_tb
14:27:46     return StackSummary.extract(walk_tb(tb), limit=limit)
14:27:46   File "/usr/lib/python3.8/traceback.py", line 347, in extract
14:27:46     for f, lineno in frame_gen:
14:27:46   File "/usr/lib/python3.8/traceback.py", line 312, in walk_tb
14:27:46     yield tb.tb_frame, tb.tb_lineno
14:27:46 AttributeError: 'json.decoder.JSONDecodeError' object has no attribute 'tb_frame'
14:27:46 + EXITCODE=1
```

**Comment by kevinyehk** [comment]
[session.tgz](https://github.com/user-attachments/files/16989655/session.tgz)
Attached the session file
