### ISSUE TITLE
LP1895168: Virtualization test tracebacks

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#148]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1895168

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-09-10 15:35:16	| 6	| Low	| False  	|

## Description
something, environmentally has changed, and the KVM test is now failing with a traceback while trying to create the metadata files on both Bionic and Focal.  

ubuntu@persianlime:~$ /usr/lib/plainbox-provider-checkbox/bin/virtualization.py --debug kvm -l virtlog.txt -i /home/ubuntu/focal-server-cloudimg-amd64.img 
DEBUG:root:Executing KVM Test
DEBUG:root:Starting KVM Test
DEBUG:root:Cloud image location specified: /home/ubuntu/focal-server-cloudimg-amd64.img
DEBUG:root:Cloud image exists locally at /home/ubuntu/focal-server-cloudimg-amd64.img
DEBUG:root:Creating cloud user-data
Traceback (most recent call last):
  File "/usr/lib/plainbox-provider-checkbox/bin/virtualization.py", line 815, in <module>
    sys.exit(main())
  File "/usr/lib/plainbox-provider-checkbox/bin/virtualization.py", line 808, in main
    args.func(args)
  File "/usr/lib/plainbox-provider-checkbox/bin/virtualization.py", line 757, in test_kvm
    result = kvm_test.start()
  File "/usr/lib/plainbox-provider-checkbox/bin/virtualization.py", line 464, in start
    self.create_cloud_disk()
  File "/usr/lib/plainbox-provider-checkbox/bin/virtualization.py", line 407, in create_cloud_disk
    data_file.write(vars()[file.replace("-", "_")])
KeyError: 'user_data'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 76, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory

The code in question has not changed sine 2014 and was previously working, so something, likely a recent change in Python. This script worked as of August 19:
https://certification.canonical.com/hardware/202002-27750/submission/177859/test/380/result/13933678/

and is failing today (September 10):
https://certification.canonical.com/hardware/202009-28230/submission/180754/test/380/result/14253908/

## Attachments
No attachments

Tags:
[]

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~mreed8855 wrote on 2020-09-15 21:36:14:
I just ran this on a Dell system freshly deployed on 20.04 and it passed. 

##### https://launchpad.net/~rodsmith wrote on 2020-09-16 22:07:09:
Even if it's caused by firmware being out of spec, our script should probably do a better job of catching the resulting error. It could then report a test failure with a helpful message, like "unsupported encoding in IPMI output," rather than fail with a stack trace. Alternatively, if we wanted to allow out-of-spec output, the "except:" clause could try other encodings.

##### https://launchpad.net/~rodsmith wrote on 2020-09-16 22:09:25:
Oops; please ignore my above comment. I have multiple bug reports open and accidentally pasted that into the wrong one.

**Comment by Hook25** [comment]
We have decided to clean up our issue tracker to systematize our approach to backlog grooming and planning. If this issue is still relevant to you, please reopen it and tag one of the maintainers or reach out on ~Checkbox on Mattermost. Going forward all issues that have received no activity for more than a year will be marked as 'stale' and closed after one week
