### ISSUE TITLE
Session Data Not Removed After Purging Checkbox Packages

### ISSUE THREAD

**Issue by mauriciocoder** [canonical/checkbox#1521]
### Enhancement Proposal

**Description:**

I encountered an issue with the Checkbox application where session data persisted even after purging the Checkbox Snap packages. After executing the following command to purge the packages:

```bash
sudo snap remove --purge checkbox checkbox22
```

I noticed that the session data in the directory `/var/tmp/checkbox-ng` was not removed. This led to complications when attempting to launch the Checkbox CLI, as the status of previously executed jobs remained in an "unsupported" state.

When I tried to run the Checkbox CLI with the command:

```bash
$ checkbox.checkbox-cli
```

I received the following output:

```
$PROVIDERPATH is defined, so following provider sources are ignored ['/home/mauricio/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
WARNING:plainbox.secure.providers.v1:Skipped file: /snap/checkbox22/current/providers/checkbox-provider-base/units/stress/suspend_cycles_reboot.md
Failed to disable unit: Unit file plainbox-autostart.service does not exist.
rm: cannot remove '/etc/systemd/system/plainbox-autostart.service': No such file or directory
Failed to disable unit: Unit file plainbox-autostart.service does not exist.
rm: cannot remove '/etc/systemd/system/plainbox-autostart.service': No such file or directory
Traceback (most recent call last):
  File "/snap/checkbox22/current/bin/checkbox-cli", line 8, in <module>
    sys.exit(main())
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/checkbox_cli.py", line 166, in main
    return subcmd.invoked(ctx)
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/subcommands.py", line 257, in invoked
    if not self._auto_resume_session(self.resume_candidates):
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/subcommands.py", line 425, in _auto_resume_session
    self._resume_session(last_session.id, None)
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/subcommands.py", line 597, in _resume_session
    raise ValueError(
ValueError: Unsupported outcome for resume not-supported
```

Despite purging and reinstalling the packages, the problem persisted. Upon investigating the source code, I discovered that Plainbox retains session data in `/var/tmp/checkbox-ng`. I manually removed the session data from this directory, and after doing so, the Checkbox CLI functioned as expected.

**Expected Behavior:**
- When a user purges the Checkbox packages, all associated session data should be removed automatically, preventing issues when reinstalling and launching the CLI.

**Steps to Reproduce:**
1. Install the Checkbox Snap package.
2. Execute a few jobs within Checkbox.
3. Purge the Checkbox package using `sudo snap remove --purge checkbox checkbox22`.
4. Reinstall Checkbox.
5. Attempt to launch the Checkbox CLI with `checkbox.checkbox-cli`.

**Additional Information:**
- Operating System: 6.8.0-45-generic #45~22.04.1-Ubuntu
- Checkbox Version: 4.1.0-dev25 - 22.04/stable
- Checkbox22 Version: 4.1.0-dev25 - latest/stable

Thank you for looking into this issue!

**Comment by mauriciocoder** [comment]
It would be helpful to have a solution for the "unsupported" job status when launching `checkbox-cli`. Perhaps invalidating the previous session and starting a new one could resolve the issue.
