### ISSUE TITLE
pw-dump command fails in checkbox environment, but it works on local environment

### ISSUE THREAD

**Issue by LiaoU3** [canonical/checkbox#1637]
### Bug Description

[audio/detect_sinks](https://github.com/canonical/checkbox/blob/197fc70ab1fc08f7497e052eb9cfb1ea93f5b5fd/providers/base/units/audio/jobs.pxu#L469) runs [pipewire_utils.py](https://github.com/canonical/checkbox/blob/197fc70ab1fc08f7497e052eb9cfb1ea93f5b5fd/providers/base/bin/pipewire_utils.py). However, it causes `subprocess.CalledProcessError` when running in checkbox environment. Interestingly, it works in local environment.

In conclusion, it was caused by running `pw-dump` in checkbox environment.

### Cert-blocker Test Case

- [x] #1638

### To Reproduce

1. sudo checkbox.shell
2. pw-dump Node

### Expected Result

Output a json format text and return code should be 0.

### Actual Result

can't create context: No such file or directory

### Environment

```
checkbox                   4.2.0-dev160        10926  24.04/beta       ce-certification-qa  classic
checkbox24                 4.2.0-dev160        392    latest/beta      ce-certification-qa  -
```
24.04, 24.10
Desktop
```
ubuntu@ubuntu-Precision-3680:/snap/checkbox24/current/providers/checkbox-provider-base/bin$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.10
Release:	24.10
Codename:	oracular
```
https://certification.canonical.com/hardware/202411-35965/

### Relevant log output

```shell
ubuntu@ubuntu-Precision-3680:/snap/checkbox24/current/providers/checkbox-provider-base/bin$ ./pipewire_utils.py detect -t audio -c sinks
device id:[53] media.class:[Audio/Sink] node.name:[alsa_output.pci-0000_04_00.0.hdmi-stereo]
device id:[54] media.class:[Audio/Sink] node.name:[alsa_output.pci-0000_00_1f.3.analog-stereo]
ubuntu@ubuntu-Precision-3680:/snap/checkbox24/current/providers/checkbox-provider-base/bin$ sudo checkbox.shell 
checkbox runtime shell, type 'exit' to quit the session
(checkbox-shell) root@ubuntu-Precision-3680:/snap/checkbox24/392/providers/checkbox-provider-base/bin# ./pipewire_utils.py detect -t audio -c sinks
can't create context: No such file or directory
Traceback (most recent call last):
  File "/snap/checkbox24/392/providers/checkbox-provider-base/bin/./pipewire_utils.py", line 721, in <module>
    sys.exit(pw.function_select(pw._args_parsing()))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/checkbox24/392/providers/checkbox-provider-base/bin/./pipewire_utils.py", line 685, in function_select
    return self.detect_device(args.type, args.clazz)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/checkbox24/392/providers/checkbox-provider-base/bin/./pipewire_utils.py", line 161, in detect_device
    clients = self._get_pw_dump("Node")
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/checkbox24/392/providers/checkbox-provider-base/bin/./pipewire_utils.py", line 104, in _get_pw_dump
    pw_dump = subprocess.check_output(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/checkbox24/current/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/checkbox24/current/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'pw-dump Node' returned non-zero exit status 255.
(checkbox-shell) root@ubuntu-Precision-3680:/snap/checkbox24/392/providers/checkbox-provider-base/bin# pw-dump Node
can't create context: No such file or directory
(checkbox-shell) root@ubuntu-Precision-3680:/snap/checkbox24/392/providers/checkbox-provider-base/bin# echo $?
255
```

### Additional context
EXternal LP bug link: https://bugs.launchpad.net/kobuk/+bug/2087902

**Comment by LiaoU3** [comment]
It seems like this problem happens not only on 24.10, but also 24.04.
```
vincent@vincent-XPS-9320:/snap/checkbox24/current/providers/checkbox-provider-base/bin$ ./pipewire_utils.py detect -t audio -c sinks
device id:[47] media.class:[Audio/Sink] node.name:[alsa_output.pci-0000_00_1f.3-platform-sof_sdw.HiFi__hw_sofsoundwire_7__sink]
device id:[48] media.class:[Audio/Sink] node.name:[alsa_output.pci-0000_00_1f.3-platform-sof_sdw.HiFi__hw_sofsoundwire_6__sink]
device id:[49] media.class:[Audio/Sink] node.name:[alsa_output.pci-0000_00_1f.3-platform-sof_sdw.HiFi__hw_sofsoundwire_5__sink]
device id:[50] media.class:[Audio/Sink] node.name:[alsa_output.pci-0000_00_1f.3-platform-sof_sdw.HiFi__hw_sofsoundwire_2__sink]
device id:[95] media.class:[Audio/Sink] node.name:[bluez_output.2C_18_09_D8_A2_3B.1]
vincent@vincent-XPS-9320:/snap/checkbox24/current/providers/checkbox-provider-base/bin$ echo $?
0
vincent@vincent-XPS-9320:/snap/checkbox24/current/providers/checkbox-provider-base/bin$ sudo checkbox.shell 
checkbox runtime shell, type 'exit' to quit the session
(checkbox-shell) root@vincent-XPS-9320:/snap/checkbox24/441/providers/checkbox-provider-base/bin# ./pipewire_utils.py detect -t audio -c sinks
can't connect: Host is down
Traceback (most recent call last):
  File "/snap/checkbox24/441/providers/checkbox-provider-base/bin/./pipewire_utils.py", line 721, in <module>
    sys.exit(pw.function_select(pw._args_parsing()))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/checkbox24/441/providers/checkbox-provider-base/bin/./pipewire_utils.py", line 685, in function_select
    return self.detect_device(args.type, args.clazz)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/checkbox24/441/providers/checkbox-provider-base/bin/./pipewire_utils.py", line 161, in detect_device
    clients = self._get_pw_dump("Node")
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/checkbox24/441/providers/checkbox-provider-base/bin/./pipewire_utils.py", line 104, in _get_pw_dump
    pw_dump = subprocess.check_output(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/checkbox24/current/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/checkbox24/current/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'pw-dump Node' returned non-zero exit status 255.
(checkbox-shell) root@vincent-XPS-9320:/snap/checkbox24/441/providers/checkbox-provider-base/bin# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
(checkbox-shell) root@vincent-XPS-9320:/snap/checkbox24/441/providers/checkbox-provider-base/bin# uname -r
6.8.0-49-generic
```

**Comment by LiaoU3** [comment]
I did not observe this issue on the latest checkbox.
```
vincent@vincent-XPS-9320:~$ sudo checkbox.shell
checkbox runtime shell, type 'exit' to quit the session
(checkbox-shell) root@vincent-XPS-9320:/home/vincent# pw-dump Node
can't connect: Host is down
vincent@vincent-XPS-9320:~$ snap list checkbox24 checkbox
Name        Version      Rev    Tracking     Publisher            Notes
checkbox    6.0.0-dev12  15675  24.04/beta   ce-certification-qa  classic
checkbox24  6.0.0-dev14  866    latest/beta  ce-certification-qa  -
```
