### ISSUE TITLE
The checkbox can not complete and it will be blocked at the 'warm-boot'. 

### ISSUE THREAD

**Issue by GabrielChenCC** [canonical/checkbox#1657]
### Bug Description

The checkbox can not complete and it will be blocked at the 'warm-boot'. 

There is a warning in journalctl log: plainbox.impl.session.resume.CorruptedSessionError: Value of key 0 is of incorrect type int

### Cert-blocker Test Case

- [ ] cert-blocker

### To Reproduce

1. Install the OEM image
2. Install the latest checkbox 4.3.0~dev35
3. Remote execute checkbox-cli
4. Select 'Desktop Preload Certification Tests for 24.04 (Automated Tests)'
5. Run all automatic test cases
6. Verify the status when the test case 'power-management/warm-reboot'
7. The test will be blocked at the warm-reboot

### Expected Result

The automatic test plan should be passed without any blocker.

### Actual Result
```
The test case will be blocker here.
---------------------------[ Running job 260 / 266 ]----------------------------
--------------------------------[ Warm reboot ]---------------------------------
ID: com.canonical.certification::power-management/warm-reboot
Category: Power Management tests
--------------------------------------------------------------------------------
Connection lost!
connection closed by peer
```
### Environment
```
u@Eiger2-1:~$ dpkg -l | grep checkbox
ii  checkbox-ng                                   4.3.0~dev35~ubuntu24.04.1                all          CheckBoxNG test runner
ii  checkbox-provider-base                        4.3.0~dev35~ubuntu24.04.1                amd64        Checkbox base provider
ii  checkbox-provider-certification-client        4.3.0~dev35~ubuntu24.04.1                all          Client Certification provider for Checkbox
ii  checkbox-provider-resource                    4.3.0~dev35~ubuntu24.04.1                amd64        Checkbox resource jobs provider
ii  checkbox-provider-tpm2                        4.3.0~dev35~ubuntu24.04.1                all          TPM 2.0 provider for Checkbox
ii  python3-checkbox-ng                           4.3.0~dev35~ubuntu24.04.1                all          CheckBoxNG test runner (Python 3 library)
ii  python3-checkbox-support                      4.3.0~dev35~ubuntu24.04.1                all          collection of Python modules used by PlainBox providers
```

### Relevant log output

```shell
Please refer to journalctl.log:
Dec 17 17:09:56 Eiger2-1 checkbox-ng.service[36636]: Undeclared exception CorruptedSessionError raised from resume_session
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]: Traceback (most recent call last):
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/bin/checkbox-cli", line 8, in <module>
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     sys.exit(main())
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:              ^^^^^^
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/checkbox_cli.py", line 166, in main
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     return subcmd.invoked(ctx)
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:            ^^^^^^^^^^^^^^^^^^^
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/agent.py", line 138, in invoked
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     SessionAssistantAgent.session_assistant.resume_by_id(
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/session/remote_assistant.py", line 721, in resume_by_id
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     meta = self.resume_session(session_id, runner_kwargs=runner_kwargs)
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/session/remote_assistant.py", line 698, in resume_session
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     return self._sa.resume_session(session_id, runner_kwargs=runner_kwargs)
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/decorators.py", line 153, in wrapper
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     raise exc
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/decorators.py", line 145, in wrapper
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     return func(*args, **kwargs)
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:            ^^^^^^^^^^^^^^^^^^^^^
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/session/assistant.py", line 574, in resume_session
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     self._manager = SessionManager.load_session(
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/session/manager.py", line 278, in load_session
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     ).resume(data, early_cb)
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:       ^^^^^^^^^^^^^^^^^^^^^^
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/session/resume.py", line 302, in resume
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     return self._resume_json(json_repr, early_cb)
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/session/resume.py", line 352, in _resume_json
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     return helper.resume_json(json_repr, early_cb)
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/session/resume.py", line 712, in resume_json
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     return self._build_SessionState(session_repr, early_cb)
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/session/resume.py", line 1280, in _build_SessionState
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     session_state = super()._build_SessionState(session_repr, early_cb)
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/session/resume.py", line 1248, in _build_SessionState
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     self._restore_SessionState_jobs_and_results(session, session_repr)
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/session/resume.py", line 779, in _restore_SessionState_jobs_and_results
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     self._process_job(session, jobs_repr, results_repr, job_id)
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/session/resume.py", line 864, in _process_job
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     result = self._build_JobResult(
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:              ^^^^^^^^^^^^^^^^^^^^^^
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/session/resume.py", line 1056, in _build_JobResult
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     cls._build_IOLogRecord(record_repr)
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/session/resume.py", line 1085, in _build_IOLogRecord
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     delay = _validate(record_repr, key=0, value_type=float)
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:   File "/usr/lib/python3/dist-packages/plainbox/impl/session/resume.py", line 1320, in _validate
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]:     raise CorruptedSessionError(error_msg)
Dec 17 17:09:57 Eiger2-1 checkbox-ng.service[36636]: plainbox.impl.session.resume.CorruptedSessionError: Value of key 0 is of incorrect type int
Dec 17 17:09:57 Eiger2-1 systemd[1]: checkbox-ng.service: Main process exited, code=exited, status=1/FAILURE
Dec 17 17:09:57 Eiger2-1 systemd[1]: checkbox-ng.service: Failed with result 'exit-code'.
Dec 17 17:09:57 Eiger2-1 systemd[1]: checkbox-ng.service: Consumed 4.260s CPU time.
Dec 17 17:09:58 Eiger2-1 systemd[1]: checkbox-ng.service: Scheduled restart job, restart counter is at 981.
Dec 17 17:09:58 Eiger2-1 systemd[1]: Started checkbox-ng.service - Checkbox Remote Service.
```

**Comment by binli** [comment]
The old version of 4.2.0~dev160  could not reproduce this issue. This issue is caused by 4.3.0~dev35.

**Comment by pseudocc** [comment]
Walk around.

```diff
diff --git a/checkbox-ng/plainbox/impl/session/resume.py b/checkbox-ng/plainbox/impl/session/resume.py
index db0db7ab8..02518279b 100644
--- a/checkbox-ng/plainbox/impl/session/resume.py
+++ b/checkbox-ng/plainbox/impl/session/resume.py
@@ -1310,7 +1310,7 @@ def _validate(obj, **flags):
     # Check if value is of correct type
     if value is not None and "value_type" in flags:
         value_type = flags["value_type"]
-        if not isinstance(value, value_type):
+        if not iscompatible(value, value_type):
             error_msg = flags.get(
                 "value_type_msg",
                 _("Value of {} is of incorrect type {}").format(
@@ -1330,3 +1330,12 @@ def _validate(obj, **flags):
             )
             raise CorruptedSessionError(error_msg)
     return value
+
+def iscompatible(obj, class_ctor):
+    if isinstance(obj, class_ctor):
+        return True
+    try:
+        class_ctor(obj)
+        return True
+    except ValueError:
+        return False
```

**Comment by GabrielChenCC** [comment]
$ sudo add-apt-repository ppa:checkbox-dev/edge
$ sudo apt install checkbox-provider-base checkbox-ng checkbox-provider-resource checkbox-provider-certification-client plainbox-provider-pc-sanity
$ dpkg -l | grep checkbox
ii  checkbox-ng                                   4.3.0~dev44~ubuntu24.04.1                all          CheckBoxNG test runner
ii  checkbox-provider-base                        4.3.0~dev44~ubuntu24.04.1                amd64        Checkbox base provider
ii  checkbox-provider-certification-client        4.3.0~dev44~ubuntu24.04.1                all          Client Certification provider for Checkbox
ii  checkbox-provider-resource                    4.3.0~dev44~ubuntu24.04.1                amd64        Checkbox resource jobs provider
ii  checkbox-provider-tpm2                        4.3.0~dev44~ubuntu24.04.1                all          TPM 2.0 provider for Checkbox
ii  python3-checkbox-ng                           4.3.0~dev44~ubuntu24.04.1                all          CheckBoxNG test runner (Python 3 library)
ii  python3-checkbox-support                      4.3.0~dev44~ubuntu24.04.1                all          collection of Python modules used by PlainBox providers

Remote execute checkbox-cli
Select 'Desktop Preload Certification Tests for 24.04 (Automated Tests)'
Run all automatic test cases
Verify the status when the test case 'power-management/warm-reboot'
The warm-reboot and cold-reboot run smoothly, no blocker here.
