### ISSUE TITLE
Rpi camera tests fail in core devices with low memory

### ISSUE THREAD

**Issue by fernando79513** [canonical/checkbox#1670]
### Bug Description

Some raspi devices are now running the camera tests and they are failing because there is no enough memory to run create some picamera MMAL components

### Cert-blocker Test Case

- [ ] cert-blocker

### To Reproduce

run:
`checkbox-cli run com.canonical.certification::camera-automated`

### Expected Result

The following camera tests pass:
    camera/multiple-resolution-images-rpi_.*
    camera/multiple-resolution-images-rpi-attachment_.*
    camera/roundtrip-qrcode_.*

### Actual Result

All of them fail because an Out of memory error in picamera

### Environment

Testing updated snap: core20
Snap version: 20241206
Snap revision: 2497
Snap channel: beta
Kernel: 5.4.0-1120-raspi
Architecture: armhf
Checkbox version: 4.3.0-dev36

### Relevant log output

```shell
Resolutions test on device: /dev/vchiq
Images will be written to:
/var/tmp/checkbox-ng/sessions/session_title-2024-12-19T16.02.08.session/session-share

mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
Traceback (most recent call last):
  File "/snap/checkbox/11427/checkbox-runtime/lib/python3.8/site-packages/picamera/camera.py", line 456, in _init_camera
    self._camera = mo.MMALCamera()
  File "/snap/checkbox/11427/checkbox-runtime/lib/python3.8/site-packages/picamera/mmalobj.py", line 2279, in __init__
    super(MMALCamera, self).__init__()
  File "/snap/checkbox/11427/checkbox-runtime/lib/python3.8/site-packages/picamera/mmalobj.py", line 631, in __init__
    mmal_check(
  File "/snap/checkbox/11427/checkbox-runtime/lib/python3.8/site-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Failed to create MMAL component b'vc.ril.camera': Out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/nest-z9ztttb2.afff2ecea64d8e296231a322b31c5eff66a357af53d02e68450b06196366454e/camera_test_rpi.py", line 63, in <module>
    sys.exit(main())
  File "/tmp/nest-z9ztttb2.afff2ecea64d8e296231a322b31c5eff66a357af53d02e68450b06196366454e/camera_test_rpi.py", line 59, in main
    return capture()
  File "/tmp/nest-z9ztttb2.afff2ecea64d8e296231a322b31c5eff66a357af53d02e68450b06196366454e/camera_test_rpi.py", line 44, in capture
    with picamera.PiCamera(resolution=res, framerate=fr) as camera:
  File "/snap/checkbox/11427/checkbox-runtime/lib/python3.8/site-packages/picamera/camera.py", line 431, in __init__
    self._init_camera(camera_num, stereo_mode, stereo_decimate)
  File "/snap/checkbox/11427/checkbox-runtime/lib/python3.8/site-packages/picamera/camera.py", line 459, in _init_camera
    raise PiCameraError(
picamera.exc.PiCameraError: Camera is not enabled. Try running 'sudo raspi-config' and ensure that the camera has been enabled.
```

**Comment by pieqq** [comment]
Recent run exhibiting this issue:

https://certification.canonical.com/hardware/201811-26649/submission/423976/

**Comment by Hook25** [comment]
We've moved away from this test
