### ISSUE TITLE
LP1918400: virtualization/verify_lxd need update to test on ubuntu core

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#179]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1918400

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2021-03-10 08:37:40	| 6	| Undecided	| False  	|

## Description
virtualization/verify_lxd need update to test on ubuntu core
Now it will be failed because it can't execute 'apt-cache'

Log:
https://certification.canonical.com/hardware/202012-28532/submission/205707/test/68747/result/17196123/

## Attachments
No attachments

Tags:
['ce-qa-concern']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~bladernr wrote on 2021-03-10 14:30:48:
DEBUG:root:Executing LXD Test
Traceback (most recent call last):
  File "/tmp/nest-0afhlxc2.460ec11461e5ca7de0e0e007ae263fcf4342ba90cf2e32ea21c373216a8e9690/virtualization.py", line 957, in <module>
    sys.exit(main())
  File "/tmp/nest-0afhlxc2.460ec11461e5ca7de0e0e007ae263fcf4342ba90cf2e32ea21c373216a8e9690/virtualization.py", line 950, in main
    args.func(args)
  File "/tmp/nest-0afhlxc2.460ec11461e5ca7de0e0e007ae263fcf4342ba90cf2e32ea21c373216a8e9690/virtualization.py", line 852, in test_lxd
    lxd_test = LXDTest(template, rootfs)
  File "/tmp/nest-0afhlxc2.460ec11461e5ca7de0e0e007ae263fcf4342ba90cf2e32ea21c373216a8e9690/virtualization.py", line 661, in __init__
    self.os_version = lsb_release.get_distro_information()["RELEASE"]
  File "/snap/checkbox-elgin/8/checkbox-runtime/usr/lib/python3/dist-packages/lsb_release.py", line 398, in get_distro_information
    distinfo = guess_debian_release()
  File "/snap/checkbox-elgin/8/checkbox-runtime/usr/lib/python3/dist-packages/lsb_release.py", line 332, in guess_debian_release
    rinfo = guess_release_from_apt()
  File "/snap/checkbox-elgin/8/checkbox-runtime/usr/lib/python3/dist-packages/lsb_release.py", line 237, in guess_release_from_apt
    releases = parse_apt_policy()
  File "/snap/checkbox-elgin/8/checkbox-runtime/usr/lib/python3/dist-packages/lsb_release.py", line 216, in parse_apt_policy
    policy = subprocess.Popen(['apt-cache','policy'],
  File "/snap/checkbox-elgin/8/checkbox-runtime/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/snap/checkbox-elgin/8/checkbox-runtime/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'apt-cache'

That is a problem in the lsb_release module where it uses apt-cache to guess certain things.

You'll need to wrap this in a try/except block and find a different way to determine the OS release on Core...

651 class LXDTest(object):
652 
653     def __init__(self, template=None, rootfs=None):
654         self.rootfs_url = rootfs
655         self.template_url = template
656         self.rootfs_tarball = None
657         self.template_tarball = None
658         self.name = 'testbed'
659         self.image_alias = uuid4().hex
660         self.default_remote = "ubuntu:"
661         self.os_version = lsb_release.get_distro_information()["RELEASE"]

You'd need to wrap line 661 in a try/except block and fall over to whatever mechanism exists in core to determine the release information typicall provided by lsb_release.



##### https://launchpad.net/~bladernr wrote on 2021-03-10 14:33:02:
Actually, a better solution, IMO would be to start building a library in checkbox-support that will handle this and can be imported whenever it's needed.

**Comment by Hook25** [comment]
We have decided to clean up our issue tracker to systematize our approach to backlog grooming and planning. If this issue is still relevant to you, please reopen it and tag one of the maintainers or reach out on ~Checkbox on Mattermost. Going forward all issues that have received no activity for more than a year will be marked as 'stale' and closed after one week
