### ISSUE TITLE
LP1898867: Ctrl-c to kill remote job traceback

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#19]
This issue was migrated from https://bugs.launchpad.net/checkbox-ng/+bug/1898867

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2020-10-07 11:57:20	| 6	| Critical	| False  	|

## Description
-----------------------------[ Running job 2 / 2 ]------------------------------
---------------------[ Stress of CPUs (very long runtime) ]---------------------
ID: com.canonical.certification::stress/cpu_stress_ng_test
Category: Stress tests
--------------------------------------------------------------------------------
STRESS_NG_CPU_TIME env var is not found, stress_ng cpu running time is default value
stress-ng: info:  [1858] dispatching hogs: 4 af-alg, 4 bsearch, 4 context, 4 cpu, 4 crypt, 4 hsearch, 4 longjmp, 4 lsearch, 4 matrix, 4 qsort, 4 str, 4 stream, 4 tsearch, 4 vecmath, 4 wcs
stress-ng: info:  [1859] stress-ng-af-alg: 23 cryptographic algorithms found in /proc/crypto
stress-ng: info:  [1859] stress-ng-af-alg: 106 cryptographic algorithms max (with defconfigs)
stress-ng: info:  [1913] stress-ng-stream: using built-in defaults as unable to determine cache details
stress-ng: info:  [1913] stress-ng-stream: stressor loosely based on a variant of the STREAM benchmark code
stress-ng: info:  [1913] stress-ng-stream: do NOT submit any of these results to the STREAM benchmark results
stress-ng: info:  [1913] stress-ng-stream: Using CPU cache size of 2048K
^CTraceback (most recent call last):
  File "/usr/local/bin/checkbox-cli", line 11, in <module>
    load_entry_point('checkbox-ng', 'console_scripts', 'checkbox-cli')()
  File "/home/sylvain/lp/checkbox-ng/checkbox_ng/launcher/checkbox_cli.py", line 123, in main
    subcmd.invoked(ctx)
  File "/home/sylvain/lp/checkbox-ng/checkbox_ng/launcher/master.py", line 155, in invoked
    self.connect_and_run(ctx.args.host, port)
  File "/home/sylvain/lp/checkbox-ng/checkbox_ng/launcher/master.py", line 179, in connect_and_run
    keep_running = self._handle_interrupt()
  File "/home/sylvain/lp/checkbox-ng/checkbox_ng/launcher/master.py", line 373, in _handle_interrupt
    self._sa.send_signal(signal.SIGKILL.value)
  File "/home/sylvain/lp/checkbox-ng/plainbox/vendor/rpyc/core/netref.py", line 253, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/home/sylvain/lp/checkbox-ng/plainbox/vendor/rpyc/core/netref.py", line 76, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/home/sylvain/lp/checkbox-ng/plainbox/vendor/rpyc/core/protocol.py", line 469, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/home/sylvain/lp/checkbox-ng/plainbox/vendor/rpyc/core/async_.py", line 102, in value
    raise self._obj
TypeError: unsupported operand type(s) for +: 'NoneType' and 'bytes'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/snap/checkbox20/current/lib/python3.8/site-packages/plainbox/vendor/rpyc/core/protocol.py", line 320, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/snap/checkbox20/current/lib/python3.8/site-packages/plainbox/vendor/rpyc/core/protocol.py", line 593, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/snap/checkbox20/current/lib/python3.8/site-packages/plainbox/impl/session/remote_assistant.py", line 703, in send_signal
    self._sa.send_signal(signal, target_user)
  File "/snap/checkbox20/current/lib/python3.8/site-packages/plainbox/impl/session/assistant.py", line 1744, in send_signal
    self._runner.send_signal(signal, target_user)
  File "/snap/checkbox20/current/lib/python3.8/site-packages/plainbox/impl/execution.py", line 377, in send_signal
    os.write(in_w, self._password_provider() + b'\n')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'bytes'

## Attachments
No attachments

Tags:
[]

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~beliaev-maksim wrote on 2022-10-21 13:34:36:
Bug was migrated to GitHub: https://github.com/canonical/checkbox/issues/18.
Bug is no more monitored here.

**Comment by kissiel** [comment]
The interruption screen got many fixes lately. This should be fixed by now. If it's not, please reopen this issue.
