### ISSUE TITLE
LP1945207: manage.py validate unhandled exceptions

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#194]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1945207

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2021-09-27 13:48:04	| 6	| Undecided	| False  	|

## Description
This is not helpful at all when running "manage.py validate"

the only clue is KeyError: 'com.canonical.certification::server-ethernet-sru' and it is a literal copy/pasta from this job:

units/ethernet/test-plan.pxu:id: server-ethernet

with one job change

 96 id: server-ethernet
 97 unit: test plan
 98 _name: Server Ethernet Tests
 99 _description: Automated ethernet tests for server certification
100 estimated_duration: 4h
101 include:
102     ethernet/info_automated_server
103     ethernet/ethtool_info
104     ethernet/ethertool_check_.*
105     ethernet/multi_iperf3_nic_device.*
106 bootstrap_include:
107     device
108     executable
109 
110 id: server-ethernet-sru
111 unit: test plan
112 _name: Server Ethernet SRU Tests
113 _description: Automated ethernet tests for server regression testing
114 estimated_duration: 4h
115 include:
116     ethernet/info_automated_server
117     ethernet/ethtool_info
118     ethernet/ethertool_check_.*
119     ethernet/multi_iperf3_nic_device_server_sru.*
120 bootstrap_include:
121     device
122     executable

so this has left me with no obvious information about why this is failing.  The only difference between the source and copy is the new job "ethernet/multi_iperf3_nic_device_server_sru.*" and that job exists in testplan.pxu, and is, itself, also a copyu/paste with only minor change to create the new job name and a slight alteration to the command: being executed.

bladernr@galactica:~/development/plainbox-provider-checkbox$ ./manage.py validate
CRITICAL plainbox.crashes: Executable 'manage.py' invoked with Namespace(command=<plainbox.provider_manager.ValidateCommand object at 0x7fd617457df0>, debug_console=False, debug_interrupt=False, deprecated=False, log_level=None, new_validation_core=True, pdb=False, strict=False, trace=[]) has crashed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plainbox/impl/clitools.py", line 560, in dispatch_and_catch_exceptions
    return self.dispatch_command(ns)
  File "/usr/lib/python3/dist-packages/plainbox/impl/clitools.py", line 556, in dispatch_command
    return ns.command.invoked(ns)
  File "/usr/lib/python3/dist-packages/plainbox/provider_manager.py", line 987, in invoked
    return self.invoked_new(ns)
  File "/usr/lib/python3/dist-packages/plainbox/provider_manager.py", line 1090, in invoked_new
    for issue in itertools.chain(early_issue_gen, issue_gen):
  File "/usr/lib/python3/dist-packages/plainbox/provider_manager.py", line 1139, in validate_units_in_context
    for issue in unit.check(context=context, live=True):
  File "/usr/lib/python3/dist-packages/plainbox/impl/unit/unit.py", line 926, in _check_gen
    for issue in validator.check_in_context(self, context):
  File "/usr/lib/python3/dist-packages/plainbox/impl/unit/unit.py", line 142, in check_in_context
    for issue in validator.check_in_context(
  File "/usr/lib/python3/dist-packages/plainbox/impl/unit/validators.py", line 583, in check_in_context
    units_with_this_value = value_map[value]
KeyError: 'com.canonical.certification::server-ethernet-sru'
Traceback (most recent call last):
  File "./manage.py", line 5, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/plainbox/provider_manager.py", line 1682, in setup
    raise SystemExit(ProviderManagerTool(definition, kwargs).main())
  File "/usr/lib/python3/dist-packages/plainbox/impl/clitools.py", line 324, in main
    return self.dispatch_and_catch_exceptions(ns)
  File "/usr/lib/python3/dist-packages/plainbox/impl/clitools.py", line 560, in dispatch_and_catch_exceptions
    return self.dispatch_command(ns)
  File "/usr/lib/python3/dist-packages/plainbox/impl/clitools.py", line 556, in dispatch_command
    return ns.command.invoked(ns)
  File "/usr/lib/python3/dist-packages/plainbox/provider_manager.py", line 987, in invoked
    return self.invoked_new(ns)
  File "/usr/lib/python3/dist-packages/plainbox/provider_manager.py", line 1090, in invoked_new
    for issue in itertools.chain(early_issue_gen, issue_gen):
  File "/usr/lib/python3/dist-packages/plainbox/provider_manager.py", line 1139, in validate_units_in_context
    for issue in unit.check(context=context, live=True):
  File "/usr/lib/python3/dist-packages/plainbox/impl/unit/unit.py", line 926, in _check_gen
    for issue in validator.check_in_context(self, context):
  File "/usr/lib/python3/dist-packages/plainbox/impl/unit/unit.py", line 142, in check_in_context
    for issue in validator.check_in_context(
  File "/usr/lib/python3/dist-packages/plainbox/impl/unit/validators.py", line 583, in check_in_context
    units_with_this_value = value_map[value]
KeyError: 'com.canonical.certification::server-ethernet-sru'

## Attachments
No attachments

Tags:
['cbox-56']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~bladernr wrote on 2021-09-27 14:07:42:
Thanks to Sylvain's help, I was able to get this to work after purging plainbox-provider-checkbox from my machine. But that does not clear this bug.

Rather than confusing tracebacks, output should be better presented for all these unit tests.  I see nothing in that output at all that indicates any "duplicate" jobs or test plans or whatever.  And doing an apt-get purge plainbox-provider-checkbox resolves the problem, but does nothing to tell me exactly what the problem is, and really, I should not have to remove checkbox in order to validate a development branch of code.

It is a perfectly valid expectation that I can have checkbox installed on my computer and still want to validate checkbox provider when developing new tests and test plans.
