### ISSUE TITLE
LP1969581: power-managment/poweroff test crash

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#210]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1969581

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-04-20 08:08:58	| 6	| Undecided	| False  	|

## Description

Device: rpi4b8g
Image: 22.04 Desktop
Checkbox package versions:
    checkbox-ng     1.17.0~ppa~ubuntu22.04.1
    plainbox-provider-checkbox  0.64.0~ppa~ubuntu22.04.1
    python3-checkbox-ng   1.17.0~ppa~ubuntu22.04.1
    python3-checkbox-support      0.54.0~ppa~ubuntu22.04.1
Test plan:
  client-cert-desktop-22-04-automated
Session type: remote

```
-------------------------[ power-management/poweroff ]--------------------------
ID: com.canonical.certification::power-management/poweroff
Category: Power Management tests
--------------------------------------------------------------------------------
DEBUG    Invoking username: ubuntu
DEBUG    Arguments: Namespace(repetitions=1, wakeup=60, min_pm_time=58, max_pm_time=300, pm_delay=5, hardware_delay=30, silent=True, log_level_str='debug', log_dir='/var/tmp/checkbox-ng/sessions/session_title-2022-04-20T07.11.59.session/session-share', pm_operation='poweroff', start=1650440639, pm_timestamp=0, append=False, total=1, suspends_before_reboot=0, fwts=False, checkbox_respawn_cmd='/var/tmp/checkbox-ng/sessions/session_title-2022-04-20T07.11.59.session/session-share/__respawn_checkbox', check_hardware_list=False, log_level=10, log_filename='/var/tmp/checkbox-ng/sessions/session_title-2022-04-20T07.11.59.session/session-share/pm_test.poweroff.1.log')
DEBUG    Extra Arguments: []
DEBUG    Enabling autologin for this user...
DEBUG    Enabling user to execute test as root...
DEBUG    Executing: "sed -i -e '$a# Automatically added by pm.py\\nubuntu ALL=NOPASSWD: /usr/bin/python3' /etc/sudoers"...
DEBUG    Writing desktop file ('/home/ubuntu/.config/autostart/pm_test.py.desktop')...
DEBUG    
[Desktop Entry]
Name=poweroff test
Comment=Verify poweroff works properly
Exec=sudo /usr/bin/python3 /usr/lib/plainbox-provider-checkbox/bin/pm_test.py -r 0 -w 60 --hardware-delay 30 --pm-delay 5 --min-pm-time 58 --max-pm-time 300 --append --total 1 --start 1650440639 --pm-timestamp 1650440639 --silent --log-level=debug --log-dir=/var/tmp/checkbox-ng/sessions/session_title-2022-04-20T07.11.59.session/session-share --suspends-before-reboot=0 --checkbox-respawn-cmd=/var/tmp/checkbox-ng/sessions/session_title-2022-04-20T07.11.59.session/session-share/__respawn_checkbox   poweroff
Type=Application
X-GNOME-Autostart-enabled=true
Hidden=false

INFO     poweroff operations remaining: 1
/tmp/nest-qvwc4yfi.373d9b0807d9e9ef62f9ceb8661f4c1908b1d37f51f18830cc3cff9a52f8c270/pm_test.py:151: PyGTKDeprecationWarning: The "buttons" argument must be a Gtk.ButtonsType enum value. Please use the "add_buttons" method for adding buttons. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  CountdownDialog(self.args.pm_operation,
Traceback (most recent call last):
  File "/tmp/nest-qvwc4yfi.373d9b0807d9e9ef62f9ceb8661f4c1908b1d37f51f18830cc3cff9a52f8c270/pm_test.py", line 1030, in <module>
    sys.exit(main())
  File "/tmp/nest-qvwc4yfi.373d9b0807d9e9ef62f9ceb8661f4c1908b1d37f51f18830cc3cff9a52f8c270/pm_test.py", line 60, in main
    operation.run()
  File "/tmp/nest-qvwc4yfi.373d9b0807d9e9ef62f9ceb8661f4c1908b1d37f51f18830cc3cff9a52f8c270/pm_test.py", line 139, in run
    self.run_pm_command()
  File "/tmp/nest-qvwc4yfi.373d9b0807d9e9ef62f9ceb8661f4c1908b1d37f51f18830cc3cff9a52f8c270/pm_test.py", line 151, in run_pm_command
    CountdownDialog(self.args.pm_operation,
  File "/tmp/nest-qvwc4yfi.373d9b0807d9e9ef62f9ceb8661f4c1908b1d37f51f18830cc3cff9a52f8c270/pm_test.py", line 488, in __init__
    super(CountdownDialog, self).__init__(title=title,
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 577, in __init__
    self._init(*args, **new_kwargs)
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 319, in new_init
    return super_init_func(self, **new_kwargs)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 519, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
```

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~jocave wrote on 2022-04-20 08:09:27:
Similar error occurs with the reboot job:

---------------------------[ Running job 164 / 228 ]----------------------------
--------------------------[ power-management/reboot ]---------------------------
ID: com.canonical.certification::power-management/reboot
Category: Power Management tests
--------------------------------------------------------------------------------
DEBUG    Invoking username: ubuntu
DEBUG    Arguments: Namespace(repetitions=1, wakeup=0, min_pm_time=0, max_pm_time=300, pm_delay=5, hardware_delay=30, silent=True, log_level_str='debug', log_dir='/var/tmp/checkbox-ng/sessions/session_title-2022-04-20T07.11.59.session/session-share', pm_operation='reboot', start=1650441800, pm_timestamp=0, append=False, total=1, suspends_before_reboot=0, fwts=False, checkbox_respawn_cmd='/var/tmp/checkbox-ng/sessions/session_title-2022-04-20T07.11.59.session/session-share/__respawn_checkbox', check_hardware_list=False, log_level=10, log_filename='/var/tmp/checkbox-ng/sessions/session_title-2022-04-20T07.11.59.session/session-share/pm_test.reboot.1.log')
DEBUG    Extra Arguments: []
DEBUG    Enabling autologin for this user...
DEBUG    Enabling user to execute test as root...
DEBUG    Executing: "sed -i -e '$a# Automatically added by pm.py\\nubuntu ALL=NOPASSWD: /usr/bin/python3' /etc/sudoers"...
DEBUG    Writing desktop file ('/home/ubuntu/.config/autostart/pm_test.py.desktop')...
DEBUG    
[Desktop Entry]
Name=reboot test
Comment=Verify reboot works properly
Exec=sudo /usr/bin/python3 /usr/lib/plainbox-provider-checkbox/bin/pm_test.py -r 0 -w 0 --hardware-delay 30 --pm-delay 5 --min-pm-time 0 --max-pm-time 300 --append --total 1 --start 1650441800 --pm-timestamp 1650441800 --silent --log-level=debug --log-dir=/var/tmp/checkbox-ng/sessions/session_title-2022-04-20T07.11.59.session/session-share --suspends-before-reboot=0 --checkbox-respawn-cmd=/var/tmp/checkbox-ng/sessions/session_title-2022-04-20T07.11.59.session/session-share/__respawn_checkbox   reboot
Type=Application
X-GNOME-Autostart-enabled=true
Hidden=false

INFO     reboot operations remaining: 1
/tmp/nest-7907g_94.a746048650c19e34b7240cf7f3b5af1f768aa5f1a4360f48ce8efc27b2b09e7d/pm_test.py:151: PyGTKDeprecationWarning: The "buttons" argument must be a Gtk.ButtonsType enum value. Please use the "add_buttons" method for adding buttons. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  CountdownDialog(self.args.pm_operation,
Traceback (most recent call last):
  File "/tmp/nest-7907g_94.a746048650c19e34b7240cf7f3b5af1f768aa5f1a4360f48ce8efc27b2b09e7d/pm_test.py", line 1030, in <module>
    sys.exit(main())
  File "/tmp/nest-7907g_94.a746048650c19e34b7240cf7f3b5af1f768aa5f1a4360f48ce8efc27b2b09e7d/pm_test.py", line 60, in main
    operation.run()
  File "/tmp/nest-7907g_94.a746048650c19e34b7240cf7f3b5af1f768aa5f1a4360f48ce8efc27b2b09e7d/pm_test.py", line 139, in run
    self.run_pm_command()
  File "/tmp/nest-7907g_94.a746048650c19e34b7240cf7f3b5af1f768aa5f1a4360f48ce8efc27b2b09e7d/pm_test.py", line 151, in run_pm_command
    CountdownDialog(self.args.pm_operation,
  File "/tmp/nest-7907g_94.a746048650c19e34b7240cf7f3b5af1f768aa5f1a4360f48ce8efc27b2b09e7d/pm_test.py", line 488, in __init__
    super(CountdownDialog, self).__init__(title=title,
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 577, in __init__
    self._init(*args, **new_kwargs)
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 319, in new_init
    return super_init_func(self, **new_kwargs)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 519, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
