### ISSUE TITLE
LP1948384: Checkbox test fails with encrypted partition

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#23]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1948384

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2021-10-22 06:22:23	| 28	| Critical	| False  	|

## Description
Running UC20 automated tests on a system that has FDE enabled.

Test: com.canonical.certification::disk/storage_device_sda requires it to mount the data partition and try to write a file to it.

The test fails with the following output:

Testing disk sda
identified as a disk...
test will be run on partition /dev/sda5
+ mount /dev/sda5 /tmp/tmpszi24803
mount: /tmp/tmpszi24803: unknown filesystem type 'crypto_LUKS'.
Traceback (most recent call last):
  File "/tmp/nest-u4v36e2x.1cbb951e7a49372b643651a046b06db20660ce01a1e0085d00cc869994722df7/storage_test.py", line 152, in <module>
    main()
  File "/tmp/nest-u4v36e2x.1cbb951e7a49372b643651a046b06db20660ce01a1e0085d00cc869994722df7/storage_test.py", line 148, in main
    disk_test(udev_name)
  File "/tmp/nest-u4v36e2x.1cbb951e7a49372b643651a046b06db20660ce01a1e0085d00cc869994722df7/storage_test.py", line 134, in disk_test
    mount(part_to_test, mount_dir)
  File "/tmp/nest-u4v36e2x.1cbb951e7a49372b643651a046b06db20660ce01a1e0085d00cc869994722df7/storage_test.py", line 50, in mount
    sp.check_call(cmd, shell=True)
  File "/snap/cdts/186/checkbox-runtime/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mount /dev/sda5 /tmp/tmpszi24803' returned non-zero exit status 32.

/dev/sda5 is the encrypted partition.

This problem was first reported in lp:1938995 but will affect any project using a DUT with FDE enabled.

## Attachments
No attachments

Tags:
['cbox-4', 'checkbox', 'test-case']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~pieq wrote on 2022-01-26 01:35:13:
This issue was found on different projects, but re-flashing the image (and re-installing and re-running checkbox) sometimes fixes the issue.

I just witnessed such a case this morning.

Yesterday, I ran an automated test plan that included this test case:

    disk/storage_device_nvme0n1

and it failed with the error mentioned in this bug description: 

    mount: /tmp/tmpcotp87ts: unknown filesystem type 'crypto_LUKS'.

The full submission is available here: https://certification.canonical.com/hardware/202109-29473/submission/246549/

After reflashing and re-installing checkbox, I ran the same automated test plan and ran the disk/* related jobs. This time, it passed, but the test job was actually different:

    disk/storage_device_dm-0

Full submission here: https://certification.canonical.com/hardware/202109-29473/submission/246773/

Comparing the udev attachments from both submissions (thanks Stanley for the tip!), we found the following differences:

In the failing run:

==========
P: /devices/virtual/block/dm-0
N: dm-0
L: 0
E: DEVPATH=/devices/virtual/block/dm-0
E: SUBSYSTEM=block
E: DEVNAME=/dev/dm-0
E: DEVTYPE=disk
E: MAJOR=253
E: MINOR=0
E: USEC_INITIALIZED=5713198
E: DM_UDEV_DISABLE_SUBSYSTEM_RULES_FLAG=1
E: DM_UDEV_DISABLE_DISK_RULES_FLAG=1
E: DM_UDEV_DISABLE_OTHER_RULES_FLAG=1
E: SYSTEMD_READY=0
E: TAGS=:snap_XXX-automount_udisksd:systemd:

P: /devices/virtual/block/dm-1
N: dm-1
L: 0
E: DEVPATH=/devices/virtual/block/dm-1
E: SUBSYSTEM=block
E: DEVNAME=/dev/dm-1
E: DEVTYPE=disk
E: MAJOR=253
E: MINOR=1
E: USEC_INITIALIZED=5713259
E: DM_UDEV_DISABLE_SUBSYSTEM_RULES_FLAG=1
E: DM_UDEV_DISABLE_DISK_RULES_FLAG=1
E: DM_UDEV_DISABLE_OTHER_RULES_FLAG=1
E: SYSTEMD_READY=0
E: TAGS=:snap_XXX-automount_udisksd:systemd:
==========

In the passing run:

==========
P: /devices/virtual/block/dm-0
N: dm-0
L: 0
S: mapper/ubuntu-data-21a5855b-b47b-488d-8958-15cb27ccb7d6
E: DEVPATH=/devices/virtual/block/dm-0
E: SUBSYSTEM=block
E: DEVNAME=/dev/dm-0
E: DEVTYPE=disk
E: MAJOR=253
E: MINOR=0
E: USEC_INITIALIZED=7825516
E: DM_UDEV_DISABLE_SUBSYSTEM_RULES_FLAG=1
E: DM_UDEV_DISABLE_DISK_RULES_FLAG=1
E: DM_UDEV_DISABLE_OTHER_RULES_FLAG=1
E: DM_UDEV_RULES=1
E: DM_UDEV_RULES_VSN=2
E: DM_NAME=ubuntu-data-21a5855b-b47b-488d-8958-15cb27ccb7d6
E: DM_UUID=CRYPT-LUKS2-a5ca6ddd720947f5858ab21661062af2-ubuntu-data-21a5855b-b47b-488d-8958-15cb27ccb7d6
E: DM_SUSPENDED=0
E: SYSTEMD_READY=0
E: DEVLINKS=/dev/mapper/ubuntu-data-21a5855b-b47b-488d-8958-15cb27ccb7d6
E: TAGS=:snap_XXX-automount_udisksd:systemd:

P: /devices/virtual/block/dm-1
N: dm-1
L: 0
S: mapper/ubuntu-save-920ff4dd-811e-4435-8c93-894c4f77608d
E: DEVPATH=/devices/virtual/block/dm-1
E: SUBSYSTEM=block
E: DEVNAME=/dev/dm-1
E: DEVTYPE=disk
E: MAJOR=253
E: MINOR=1
E: USEC_INITIALIZED=7825622
E: DM_UDEV_DISABLE_SUBSYSTEM_RULES_FLAG=1
E: DM_UDEV_DISABLE_DISK_RULES_FLAG=1
E: DM_UDEV_DISABLE_OTHER_RULES_FLAG=1
E: DM_UDEV_RULES=1
E: DM_UDEV_RULES_VSN=2
E: DM_NAME=ubuntu-save-920ff4dd-811e-4435-8c93-894c4f77608d
E: DM_UUID=CRYPT-LUKS2-2383c989679e46dda2ae1c829035760e-ubuntu-save-920ff4dd-811e-4435-8c93-894c4f77608d
E: DM_SUSPENDED=0
E: SYSTEMD_READY=0
E: DEVLINKS=/dev/mapper/ubuntu-save-920ff4dd-811e-4435-8c93-894c4f77608d
E: TAGS=:snap_XXX-automount_udisksd:systemd:
==========

In the run that passes, we have the following additional information in udev attachment:

==========
for dm-0:

S: mapper/ubuntu-data-21a5855b-b47b-488d-8958-15cb27ccb7d6
E: DM_UDEV_RULES=1
E: DM_UDEV_RULES_VSN=2
E: DM_NAME=ubuntu-data-21a5855b-b47b-488d-8958-15cb27ccb7d6
E: DM_UUID=CRYPT-LUKS2-a5ca6ddd720947f5858ab21661062af2-ubuntu-data-21a5855b-b47b-488d-8958-15cb27ccb7d6
E: DM_SUSPENDED=0
E: DEVLINKS=/dev/mapper/ubuntu-data-21a5855b-b47b-488d-8958-15cb27ccb7d6

for dm-1:

S: mapper/ubuntu-save-920ff4dd-811e-4435-8c93-894c4f77608d
E: DM_UDEV_RULES=1
E: DM_UDEV_RULES_VSN=2
E: DM_NAME=ubuntu-save-920ff4dd-811e-4435-8c93-894c4f77608d
E: DM_UUID=CRYPT-LUKS2-2383c989679e46dda2ae1c829035760e-ubuntu-save-920ff4dd-811e-4435-8c93-894c4f77608d
E: DM_SUSPENDED=0
E: DEVLINKS=/dev/mapper/ubuntu-save-920ff4dd-811e-4435-8c93-894c4f77608d
==========

##### https://launchpad.net/~pieq wrote on 2022-05-12 03:14:49:
I don't think this has been fixed, as there is no comment nor a link to a MR fixing this issue.

Setting it to "Confirmed" again.

##### https://launchpad.net/~pieq wrote on 2022-05-12 03:17:39:
I guess this bug is somehow related to what's going on in lp:1959077, but I'm not sure if it's a duplicate or not.
