### ISSUE TITLE
LP1982742: disk/disk_stress_ng_* fail due to no argument thread_count

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#239]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1982742

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-07-25 08:59:40	| 6	| Undecided	| False  	|

## Description
[Summary]
disk/disk_stress_ng_* fail due to no argument thread_count.

########
ID: com.canonical.certification::disk/disk_stress_ng_mmcblk0
Category: com.canonical.plainbox::disk
... 8< -------------------------------------------------------------------------
Found STRESS_NG_DISK_TIME env var, stress_ng disk running time is now: 240 seconds
Using test directory: '//tmp/stress-ng-e2f99c02-0bf3-11ed-83d7-df1c5aaefbc1'
Estimated total run time is 104 minutes

Traceback (most recent call last):
  File "/tmp/nest-m0qxvouz.2ff0da9a4342b55a311e5de24871221cac0428a0fad46926117f56099d17d68c/stress_ng_test.py", line 377, in <module>
    sys.exit(main())
  File "/tmp/nest-m0qxvouz.2ff0da9a4342b55a311e5de24871221cac0428a0fad46926117f56099d17d68c/stress_ng_test.py", line 365, in main
    retval = args.func(args)
  File "/tmp/nest-m0qxvouz.2ff0da9a4342b55a311e5de24871221cac0428a0fad46926117f56099d17d68c/stress_ng_test.py", line 297, in stress_disk
    test_object = StressNg(stressors=stressor.split(),
TypeError: __init__() missing 1 required positional argument: 'thread_count'
#######

It could be relate with this MR[1].
[1] https://code.launchpad.net/~alanec/plainbox-provider-checkbox/+git/plainbox-provider-checkbox/+merge/424665

[snap information]
checkbox20  1.29.dev  1005  latest/edge

## Attachments
No attachments

Tags:
[]

**Comment by Hook25** [comment]
Thread count is no longer a positional argument, now it is a kwarg with a default value, so this should not happen anymore. 

If you still have this problem please re-open this issue.
