### ISSUE TITLE
Unable to ping gateway after hotplug ethernet (command arp delay)

### ISSUE THREAD

**Issue by baconYao** [canonical/checkbox#291]
### Problem

The test for hotplugging the Ethernet cable detected the cable being disconnected and reconnected but failed with a Python error when it tried to ping the internet.

[Checkbox job `com.canonical.certification::ethernet/hotplug-enp44s0` output]

stdout
------
Press enter and unplug the ethernet cable from the port enp44s0 of the System.
After 15 seconds plug it back in.
Checkbox session may be interrupted but it should come back up.
Waiting for cable to get disconnected.
..Cable unplugged!
Waiting for the cable to get connected.
.......Cable detected!
Adjusting deadline to 3 seconds to fit 2 pings
Desired ip address 10.102.88.1 is not reachable from enp44s0, using None instead
Desired ip address 10.102.88.1 is not reachable from enp44s0, using None instead
Desired ip address 10.102.88.1 is not reachable from enp44s0, using None instead
Desired ip address 10.102.88.1 is not reachable from enp44s0, using None instead
Desired ip address 10.102.88.1 is not reachable from enp44s0, using None instead
Desired ip address 10.102.88.1 is not reachable from enp44s0, using None instead
Desired ip address 10.102.88.1 is not reachable from enp44s0, using None instead
Desired ip address 10.102.88.1 is not reachable from enp44s0, using None instead
Desired ip address 10.102.88.1 is not reachable from enp44s0, using None instead
Desired ip address 10.102.88.1 is not reachable from enp44s0, using None instead
Checking connectivity to None
No Internet connection

stderr
------
Traceback (most recent call last):
  File "/tmp/nest-mdntusa5.b55e8b052d3b03d6edcb4f61f397be05d950d3a89b0bbc631742a163cb23bb47/gateway_ping_test.py", line 308, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/tmp/nest-mdntusa5.b55e8b052d3b03d6edcb4f61f397be05d950d3a89b0bbc631742a163cb23bb47/gateway_ping_test.py", line 286, in main
    if ping_summary.get('cause'):
AttributeError: 'NoneType' object has no attribute 'get'

[Failure rate]
Over 90%

### To Reproduce

1. Install iotg server 22.04 image
2. Install checkbox
    ```
    $ sudo snap install checkbox22
    $ sudo snap install checkbox --edge --classic
    ```
3. Choose `com.canonical.certification::client-cert-iot-server-22-04-manual` test plan
4. Run `ethernet/hotplug-{interface}` job

### Environment

- OS: Server 22.04 LTS
- Checkbox Type: Snap
- Checkbox Version:
  - Version: 2.4.dev
  - Rev: 2020
  - Tracking: latest/edge
  - Notes: classic
- Hardware being tested:
  - CID: 202110-29509
  - SKU: aaeon-tgl
  - system-manufacturer: AAEON
  - system-product-name: UPX-TGL01
  - bios-version: UXTGBM13
  - CPU: Intel(R) Celeron(R) 6305E @ 1.80GHz (2x)
  - GPU: 00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:9a78] (rev 01)
  - kernel-version: 5.15.0-1016-intel-iotg

### Additional context

I do some investigate and record the video. 
I suspect the command `arp` causes this problem.
https://github.com/canonical/checkbox/blob/main/providers/base/bin/gateway_ping_test.py#L153

I used the `enp44s0` interface as example

---
- [0:00 - 0:08]
  - Show the status and ip address  of enp44s0 interface is working
- [0:08 - 0:29]
  - Left window
    - watch the enp44s0 interface via `watch -n 0.1 networkctl status --no-pager --no-legend enp44s0`
  - Right window
    - watch the arp via `watch -c -n 0.1 arp -a -n`
- [0:30]
  - Unplug the ethernet cable
    - So we can observe the change in both window
- [0:37]
  - Plug  the cable back
    - We can find the change happened in left windows (Got ip address, status became online from offline)
    - _However, there was no change in the right window. It should have change while the cable was plugged back ideally._
- [0:51]
  - Until the 0:51 second, We got the enp44s0 interface reoprted by arp command.
  
Therefore, we could not get the host (we got the None), it caused checkbox didn't know who was the candidate to be ping via interface `enp44s0`

[hotplug-ethernet-ping-problem.webm](https://user-images.githubusercontent.com/8318678/210733420-5f9c18fc-747b-4c37-924e-ece341cd8bb8.webm)

**Comment by baconYao** [comment]
Issue can be reproduced on IoTG Desktop 22.04 Beta image as well. But the failure rate is super low since the updated time of info from arp command is faster than Server image.

**Comment by pieqq** [comment]
This issue was also reported by ODM.

**Comment by rickwu666666** [comment]
Found the same issue on project Baytown

**Comment by Hook25** [comment]
We have decided to clean up our issue tracker to systematize our approach to backlog grooming and planning. If this issue is still relevant to you, please reopen it and tag one of the maintainers or reach out on ~Checkbox on Mattermost. Going forward all issues that have received no activity for more than a year will be marked as 'stale' and closed after one week
