### ISSUE TITLE
ERROR: test_multiple (test_fan_reaction.FanMonitorTests)

### ISSUE THREAD

**Issue by KaiChuan-Hsieh** [canonical/checkbox#475]
### Bug Description

Got error when propose a PR, however, it shows the fail unrelated to my PR.

https://github.com/canonical/checkbox/actions/runs/5020277282/jobs/9001604703?pr=474

### To Reproduce

1. Create a PR
2. github run the workflow automatically
3. see the fail and block the merge

### Environment

on github.com

### Relevant log output

```shell
======================================================================
ERROR: test_multiple (test_fan_reaction.FanMonitorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "/home/runner/work/checkbox/checkbox/providers/base/tests/test_fan_reaction.py", line 56, in test_multiple
    fan_mon = FanMonitor()
  File "/home/runner/work/checkbox/checkbox/providers/base/bin/fan_reaction_test.py", line 61, in __init__
    raise SystemExit(0)
SystemExit: 0

----------------------------------------------------------------------
Ran 1116 tests in 37.246s

FAILED (errors=1)
Fan monitoring interface not found in SysFS
Not able to access /tmp/tmpcil4jfgd/device/class
Not able to access /tmp/tmpcil4jfgd/device/class
Fan monitoring interface not found in SysFS
Found recovery partiion
ERROR: InvocationError for command /home/runner/work/checkbox/checkbox/providers/base/.tox/py38/bin/python3 manage.py test (exited with code 1)
py310 create: /home/runner/work/checkbox/checkbox/providers/base/.tox/py310
SKIPPED: InterpreterNotFound: python3.10
___________________________________ summary ____________________________________
  py35: commands succeeded
SKIPPED:  py36: InterpreterNotFound: python3.6
ERROR:   py38: commands failed
SKIPPED:  py310: InterpreterNotFound: python3.10
Error: Process completed with exit code 1.
```

**Comment by kissiel** [comment]
The test should not create a real instance of FanMonitor that looks at SYSFS for the real fan. This has to be fixed.
