### ISSUE TITLE
udev_resource.py -f PARTITION failed with error

### ISSUE THREAD

**Issue by seankingyang** [canonical/checkbox#482]
### Bug Description

`udev_resource.py -f PARTITION` failed with error and impact on "usb/storage-detect" test case 

[`com.canonical.certification::usb/storage-detect` output]
```
Traceback (most recent call last):
  File "/tmp/nest-ksyc7yi4.5898582bde834e198d8c971d79f8e1aa6851b304be424661f5e7be4c435e3acd/udev_resource.py", line 140, in <module>
    main()
  File "/tmp/nest-ksyc7yi4.5898582bde834e198d8c971d79f8e1aa6851b304be424661f5e7be4c435e3acd/udev_resource.py", line 133, in main
    if filter_by_categories(udev, args.filter) == 0:
  File "/tmp/nest-ksyc7yi4.5898582bde834e198d8c971d79f8e1aa6851b304be424661f5e7be4c435e3acd/udev_resource.py", line 50, in filter_by_categories
    for device in udev.run():
  File "/usr/lib/python3/dist-packages/checkbox_support/parsers/udevadm.py", line 1282, in run
    elif device.category == 'BLUETOOTH':
  File "/usr/lib/python3/dist-packages/checkbox_support/parsers/udevadm.py", line 284, in category
    if self.bus == "bluetooth":
  File "/usr/lib/python3/dist-packages/checkbox_support/parsers/udevadm.py", line 218, in bus
    return self._stack[-2]._environment.get("SUBSYSTEM")
IndexError: list index out of range
```

[run `udev_resource.py -f PARTITION`]
```
ubuntu@ubuntu:/usr/lib/checkbox-provider-resource/bin$ ./udev_resource.py -f PARTITION
Traceback (most recent call last):
  File "/usr/lib/checkbox-provider-resource/bin/./udev_resource.py", line 140, in <module>
    main()
  File "/usr/lib/checkbox-provider-resource/bin/./udev_resource.py", line 133, in main
    if filter_by_categories(udev, args.filter) == 0:
  File "/usr/lib/checkbox-provider-resource/bin/./udev_resource.py", line 50, in filter_by_categories
    for device in udev.run():
  File "/usr/lib/python3/dist-packages/checkbox_support/parsers/udevadm.py", line 1282, in run
    elif device.category == 'BLUETOOTH':
  File "/usr/lib/python3/dist-packages/checkbox_support/parsers/udevadm.py", line 284, in category
    if self.bus == "bluetooth":
  File "/usr/lib/python3/dist-packages/checkbox_support/parsers/udevadm.py", line 218, in bus
    return self._stack[-2]._environment.get("SUBSYSTEM")
IndexError: list index out of range
```

[`lsblk` output]
```
ubuntu@ubuntu:~$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
loop0         7:0    0     4K  1 loop  /snap/bare/5
loop1         7:1    0  37.8M  1 loop  /snap/bugit/13
loop2         7:2    0  55.6M  1 loop  /snap/core18/2745
loop3         7:3    0  63.3M  1 loop  /snap/core20/1879
loop4         7:4    0  63.5M  1 loop  /snap/core20/1891
loop5         7:5    0  73.1M  1 loop  /snap/core22/634
loop6         7:6    0   242M  1 loop  /snap/firefox/2667
loop7         7:7    0 349.7M  1 loop  /snap/gnome-3-38-2004/140
loop8         7:8    0 460.6M  1 loop  /snap/gnome-42-2204/102
loop9         7:9    0  91.7M  1 loop  /snap/gtk-common-themes/1535
loop10        7:10   0  12.3M  1 loop  /snap/snap-store/959
loop11        7:11   0  53.2M  1 loop  /snap/snapd/19122
loop12        7:12   0   9.8M  1 loop  /snap/sosreport/139
loop13        7:13   0   452K  1 loop  /snap/snapd-desktop-integration/83
sda           8:0    1  14.4G  0 disk  
└─sda1        8:1    1  14.4G  0 part  /media/ubuntu/07AE-0828
nvme1n1     259:0    0 238.5G  0 disk  
├─md126       9:126  0 906.2G  0 raid0 
│ ├─md126p1 259:8    0 238.4M  0 part  /boot/efi
│ ├─md126p2 259:9    0   7.6G  0 part  
│ └─md126p3 259:10   0 898.3G  0 part  /var/snap/firefox/common/host-hunspell
│                                      /
└─md127       9:127  0     0B  0 md    
nvme3n1     259:1    0 238.5G  0 disk  
├─md126       9:126  0 906.2G  0 raid0 
│ ├─md126p1 259:8    0 238.4M  0 part  /boot/efi
│ ├─md126p2 259:9    0   7.6G  0 part  
│ └─md126p3 259:10   0 898.3G  0 part  /var/snap/firefox/common/host-hunspell
│                                      /
└─md127       9:127  0     0B  0 md    
nvme2n1     259:2    0 238.5G  0 disk  
├─md126       9:126  0 906.2G  0 raid0 
│ ├─md126p1 259:8    0 238.4M  0 part  /boot/efi
│ ├─md126p2 259:9    0   7.6G  0 part  
│ └─md126p3 259:10   0 898.3G  0 part  /var/snap/firefox/common/host-hunspell
│                                      /
└─md127       9:127  0     0B  0 md    
nvme4n1     259:3    0 238.5G  0 disk  
├─md126       9:126  0 906.2G  0 raid0 
│ ├─md126p1 259:8    0 238.4M  0 part  /boot/efi
│ ├─md126p2 259:9    0   7.6G  0 part  
│ └─md126p3 259:10   0 898.3G  0 part  /var/snap/firefox/common/host-hunspell
│                                      /
└─md127       9:127  0     0B  0 md    
nvme0n1     259:4    0 953.9G  0 disk  
├─nvme0n1p1 259:5    0 238.4M  0 part  
├─nvme0n1p2 259:6    0   5.7G  0 part  
└─nvme0n1p3 259:7    0 947.9G  0 part
```

### To Reproduce

1. Run `udev_resource.py -f PARTITION`

### Environment

checkbox-ng: 2.6
checkbox-support: 2.6
checkbox-provider-base: 2.6
checkbox-provider-certification-client: 2.6
checkbox-provider-resource: 2.6
checkbox-provider-tpm2: 2.6
com.canonical.ce:oem: 1.0

CID: 202305-31614
SKU: CRS-SPR-PLT-L10-C1
Image: canonical-oem-somerville-jammy-amd64-20220504-33+jellyfish-corsola+X61
system-manufacturer: Dell Inc.
system-product-name: Precision 7960 Tower
bios-version: 1.0.0
CPU: Intel(R) Xeon(R) w5-3435X (32x)
GPU: 0000:16:00.0 VGA compatible controller [0300]: NVIDIA Corporation Device [10de:26b1] (rev a1)
nvidia-driver-version: 525.116.04
kernel-version: 6.1.0-1012-oem

Storage: RAID on mode
Addon card: VROC ZOOM 4 (DP/N: 3J7WX)
Create RAID0 on Zoom 4 card

### Additional context

submission: https://certification.canonical.com/hardware/202305-31614/submission/313841/

**Comment by yphus** [comment]
@seankingyang Could you please attach to this bug the output of the following commands?

- `lsblk -i -n -P -o KNAME,TYPE,MOUNTPOINT`
- `udevadm info --export-db`

**Comment by yphus** [comment]
No need to run the commands, both outputs are in the submission

**Comment by seankingyang** [comment]
After checking with the HW RAID(ie MegaRAID 9660), there issue will not occur.
This issue seems only occurs on Virtual RAID (Zoom card).

**Comment by stanley31huang** [comment]
We also seen this issue on DELL Edge Gateway 5200. On the 5200, we have created a RAID1 by the Intel RST controller.

```
ubuntu@ubuntu:~$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
loop0         7:0    0 289.3M  1 loop  /snap/checkbox22/726
loop1         7:1    0  16.1M  1 loop  /snap/checkbox-ce-oem/110
loop2         7:2    0  16.2M  1 loop  /snap/checkbox-ce-oem/138
loop3         7:3    0  54.6M  1 loop  /snap/checkbox-iiotg-classic/78
loop4         7:4    0  55.7M  1 loop  /snap/core18/2812
loop5         7:5    0  63.9M  1 loop  /snap/core20/2105
loop6         7:6    0  74.1M  1 loop  /snap/core22/1033
loop7         7:7    0  19.4M  1 loop  /snap/lms/75
loop8         7:8    0  16.3M  1 loop  /snap/lms/76
loop9         7:9    0 111.9M  1 loop  /snap/lxd/24322
loop10        7:10   0  40.9M  1 loop  /snap/snapd/20290
loop11        7:11   0  40.4M  1 loop  /snap/snapd/20671
sda           8:0    0   1.9T  0 disk  
├─md126       9:126  0   1.9T  0 raid1 
│ ├─md126p1 259:0    0    50M  0 part  /boot/efi
│ └─md126p2 259:1    0   1.9T  0 part  /
└─md127       9:127  0     0B  0 md    
sdb           8:16   0   1.9T  0 disk  
├─md126       9:126  0   1.9T  0 raid1 
│ ├─md126p1 259:0    0    50M  0 part  /boot/efi
│ └─md126p2 259:1    0   1.9T  0 part  /
└─md127       9:127  0     0B  0 md

error log:
Traceback (most recent call last):
  File "/tmp/nest-sm_eiuj3.5898582bde834e198d8c971d79f8e1aa6851b304be424661f5e7be4c435e3acd/udev_resource.py", line 140, in <module>
    main()
  File "/tmp/nest-sm_eiuj3.5898582bde834e198d8c971d79f8e1aa6851b304be424661f5e7be4c435e3acd/udev_resource.py", line 133, in main
    if filter_by_categories(udev, args.filter) == 0:
  File "/tmp/nest-sm_eiuj3.5898582bde834e198d8c971d79f8e1aa6851b304be424661f5e7be4c435e3acd/udev_resource.py", line 50, in filter_by_categories
    for device in udev.run():
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_support/parsers/udevadm.py", line 1289, in run
    elif device.category == 'BLUETOOTH':
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_support/parsers/udevadm.py", line 284, in category
    if self.bus == "bluetooth":
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_support/parsers/udevadm.py", line 218, in bus
    return self._stack[-2]._environment.get("SUBSYSTEM")
IndexError: list index out of range
```

**Comment by seankingyang** [comment]
#952 is merged, so mark this issue as closed
