### ISSUE TITLE
Unable to do iperf testing since script throws ZeroDivisionError error

### ISSUE THREAD

**Issue by baconYao** [canonical/checkbox#539]
### I ran into a problem which gives the error like below

```
-----------------------[ Iperf3 stress testing for eth0 ]-----------------------
ID: com.canonical.certification::ethernet/iperf3_eth0
Category: Ethernet Device tests
--------------------------------------------------------------------------------
INFO:root:Testing eth0 against 10.102.88.220
INFO:root:Have successfully pinged 10.102.88.220 on eth0
INFO:root:-------------------- Test Run Number 1 --------------------
INFO:root:Using 1 thread.
WARNING:root:WARNING: Could not find the NUMA node associated with eth0!
WARNING:root:Setting the association to NUMA node 0, which may not be optimal!
INFO:root:NUMA node of eth0 is 0....
Traceback (most recent call last):
  File "/tmp/nest-pmj_1dlm.733188759a536d454588eb1b832197fe0ac6141c07b5ee7f5b36d7837164df28/network.py", line 1023, in <module>
    sys.exit(main())
  File "/tmp/nest-pmj_1dlm.733188759a536d454588eb1b832197fe0ac6141c07b5ee7f5b36d7837164df28/network.py", line 1019, in main
    return args.func(args)
  File "/tmp/nest-pmj_1dlm.733188759a536d454588eb1b832197fe0ac6141c07b5ee7f5b36d7837164df28/network.py", line 783, in interface_test
    error_number = run_test(args, test_target)
  File "/tmp/nest-pmj_1dlm.733188759a536d454588eb1b832197fe0ac6141c07b5ee7f5b36d7837164df28/network.py", line 614, in run_test
    error_number = iperf_benchmark.run()
  File "/tmp/nest-pmj_1dlm.733188759a536d454588eb1b832197fe0ac6141c07b5ee7f5b36d7837164df28/network.py", line 292, in run
    core = core_list[thread_num % len(core_list)]
ZeroDivisionError: integer division or modulo by zero
--------------------------------------------------------------------------------
Outcome: job failed
```

### What happened?

According to the [PR#479](https://github.com/canonical/checkbox/pull/479) , it tries to find the number of NUMA node via `lscpu` command, however, there is no NUMA node on RPI 4. This result causes the problem above.

```
u@u-desktop:/sys/class/net/eth0/device$ lscpu
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               ARM
  Model name:            Cortex-A72
    Model:               3
    Thread(s) per core:  1
    Core(s) per cluster: 4
    Socket(s):           -
    Cluster(s):          1
    Stepping:            r0p3
    CPU max MHz:         1800.0000
    CPU min MHz:         600.0000
    BogoMIPS:            108.00
    Flags:               fp asimd evtstrm crc32 cpuid
Caches (sum of all):     
  L1d:                   128 KiB (4 instances)
  L1i:                   192 KiB (4 instances)
  L2:                    1 MiB (1 instance)
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; __user pointer sanitization
  Spectre v2:            Vulnerable
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

```
u@u-desktop:/sys/class/net/eth0/device$ ls -al
total 0
drwxr-xr-x  5 root root    0  一   1  1970 .
drwxr-xr-x 10 root root    0  一   1  1970 ..
lrwxrwxrwx  1 root root    0  一   1  1970 driver -> ../../../../bus/platform/drivers/bcmgenet
-rw-r--r--  1 root root 4096  六   7 09:45 driver_override
-r--r--r--  1 root root 4096  六   7 09:45 modalias
drwxr-xr-x  3 root root    0  一   1  1970 net
lrwxrwxrwx  1 root root    0  六   7 09:45 of_node -> ../../../../firmware/devicetree/base/scb/ethernet@7d580000
drwxr-xr-x  2 root root    0  六   7 09:45 power
lrwxrwxrwx  1 root root    0  一   1  1970 subsystem -> ../../../../bus/platform
-rw-r--r--  1 root root 4096  一   1  1970 uevent
drwxr-xr-x  4 root root    0  一   1  1970 unimac-mdio.-19
```

### To Reproduce

1. Flash Jammy Desktop Image to RPI 4
2. Install Checkbox via the following commands
```
$ sudo snap install checkbox22
$ sudo snap install checkbox
```
3. Configure the IP address of the Iperf Server via `$ sudo checkbox.configure TEST_TARGET_IPERF=<ip address of iperf server>`
4. Run iperf test case in `com.canonical.certification::client-cert-desktop-22-04-stress` test plan

### Environment

- Device: Raspberry PI 4
- OS: 22.04 Desktop image (I downloaded it from the [Ubuntu Official Website](https://ubuntu.com/download/raspberry-pi/thank-you?version=22.04.2&architecture=desktop-arm64+raspi))
- Snap:
  ```
   u@u-desktop:~$ snap list
   Name                       Version           Rev    Tracking         Publisher            Notes
   checkbox                   2.6               2418   latest/stable    ce-certification-qa  classic
   checkbox22                 2.6               372    latest/stable    ce-certification-qa  -
  ```

**Comment by bladernr** [comment]
This was the bug Rod requested as he looks into this issue...

**Comment by rodwsmith** [comment]
@baconYao , I've created a PR to fix this bug:

https://github.com/canonical/checkbox/pull/546

Could you please give it a try with that changed script? I don't have a Raspberry Pi 4, and my attempt to re-create the bug on an earlier Raspberry Pi was unsuccessful, so I had to fake it by commenting out some code in a test version of the script. My fix works on that version, and I expect it should work on your real system, but verification would be desirable. Please review my fix and approve it if it works. Thanks!
