### ISSUE TITLE
Checkbox remote crashes when selecting "Kill test in progress and move on to next" in the interrupt menu

### ISSUE THREAD

**Issue by pieqq** [canonical/checkbox#550]
### Bug Description

When using the remote menu to "Kill test in progress and move on to next" while an automated job is running, Checkbox crashes with the following traceback:

```
^CTraceback (most recent call last):
  File "/home/pieq/.venvs/checkbox/bin/checkbox-cli", line 33, in <module>
    sys.exit(load_entry_point('checkbox-ng', 'console_scripts', 'checkbox-cli')())
  File "/mnt/documents/dev/work/checkbox/checkbox-ng/checkbox_ng/launcher/checkbox_cli.py", line 140, in main
    subcmd.invoked(ctx)
  File "/mnt/documents/dev/work/checkbox/checkbox-ng/checkbox_ng/launcher/master.py", line 152, in invoked
    self.connect_and_run(ctx.args.host, port)
  File "/mnt/documents/dev/work/checkbox/checkbox-ng/checkbox_ng/launcher/master.py", line 185, in connect_and_run
    keep_running = self._handle_interrupt()
  File "/mnt/documents/dev/work/checkbox/checkbox-ng/checkbox_ng/launcher/master.py", line 418, in _handle_interrupt
    self._sa.send_signal(signal.SIGKILL.value)
  File "/mnt/documents/dev/work/checkbox/checkbox-ng/plainbox/vendor/rpyc/core/netref.py", line 240, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/mnt/documents/dev/work/checkbox/checkbox-ng/plainbox/vendor/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/mnt/documents/dev/work/checkbox/checkbox-ng/plainbox/vendor/rpyc/core/protocol.py", line 718, in sync_request
    return _async_res.value
  File "/mnt/documents/dev/work/checkbox/checkbox-ng/plainbox/vendor/rpyc/core/async_.py", line 108, in value
    raise self._obj
_get_exception_class.<locals>.Derived: unsupported operand type(s) for +: 'NoneType' and 'bytes'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/mnt/documents/dev/work/checkbox/checkbox-ng/plainbox/vendor/rpyc/core/protocol.py", line 359, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/mnt/documents/dev/work/checkbox/checkbox-ng/plainbox/vendor/rpyc/core/protocol.py", line 837, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/mnt/documents/dev/work/checkbox/checkbox-ng/plainbox/impl/session/remote_assistant.py", line 722, in send_signal
    self._sa.send_signal(signal, target_user)
  File "/mnt/documents/dev/work/checkbox/checkbox-ng/plainbox/impl/session/assistant.py", line 1764, in send_signal
    self._runner.send_signal(signal, target_user)
  File "/mnt/documents/dev/work/checkbox/checkbox-ng/plainbox/impl/execution.py", line 381, in send_signal
    os.write(in_w, self._password_provider() + b'\n')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'bytes'
```

### To Reproduce

1. Setup a Checkbox virtual environment as described in the contributing guide
2. As root, run the service side:
    - `sudo -i`
    - `source /pat/to/venv/checkbox/bin/activate`
    - `checkbox-cli service`
 3. As normal user, execute Checkbox (`checkbox-cli remote 127.0.0.1`), select a test plan and run it
 4. While Checkbox is running a test, press `Ctrlc+C` to show the UI
 5. Select the second item: "Kill test in progress and move on to next"

Expected behavior:
- Checkbox goes to the next test

Actual behavior:
- Checkbox remote crashes with the traceback shown above

### Environment

- OS: Ubuntu 22.04
- Checkbox version: latest from `main` (v2.7)
- Python: 3.10.6

**Comment by Hook25** [comment]
We have decided to clean up our issue tracker to systematize our approach to backlog grooming and planning. If this issue is still relevant to you, please reopen it and tag one of the maintainers or reach out on ~Checkbox on Mattermost. Going forward all issues that have received no activity for more than a year will be marked as 'stale' and closed after one week
