### ISSUE TITLE
LP1982291: [Checkbox SNAP] Checkbox crash while running thunderbolt3/insert test

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#57]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1982291

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-07-20 05:06:35	| 6	| Critical	| False  	|

## Description
[Summary]
Checkbox crash while running the thunderbolt3/insert test

[Steps to reproduce]
1. Install checkbox20 and checkbox snaps
2. Issue command to perform thunderbolt3/insert test
checkbox.checkbox-cli run com.canonical.certification::after-suspend-thunderbolt3/insert

[Expected result]
thunderbolt3/insert test passed

[Actual result]
thunderbolt3/insert test failed, and the thunderbolt3/storage and thunderbolt3/remove tests shall has the same problem.

[Failure rate]

[Checkbox job `com.canonical.certification::after-suspend-thunderbolt3/insert` output]

stdout
------

INSERT NOW

stderr
------
Traceback (most recent call last):
  File "/snap/checkbox-iiotg/21/checkbox-runtime/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/snap/checkbox-iiotg/21/checkbox-runtime/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/snap/checkbox-iiotg/21/checkbox-runtime/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.UDisks': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/nest-pgp_x2ar.30d6185b436b5daa6a2fc33c1a0806378add146da5fd3b86324e64b4940af1fb/removable_storage_watcher.py", line 940, in <module>
    sys.exit(main())
  File "/tmp/nest-pgp_x2ar.30d6185b436b5daa6a2fc33c1a0806378add146da5fd3b86324e64b4940af1fb/removable_storage_watcher.py", line 934, in main
    return listener.check(args.timeout)
  File "/tmp/nest-pgp_x2ar.30d6185b436b5daa6a2fc33c1a0806378add146da5fd3b86324e64b4940af1fb/removable_storage_watcher.py", line 104, in check
    self._starting_devices = self.get_existing_devices()
  File "/tmp/nest-pgp_x2ar.30d6185b436b5daa6a2fc33c1a0806378add146da5fd3b86324e64b4940af1fb/removable_storage_watcher.py", line 226, in get_existing_devices
    ud_manager_obj = self._bus.get_object("org.freedesktop.UDisks",
  File "/snap/checkbox-iiotg/21/checkbox-runtime/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/snap/checkbox-iiotg/21/checkbox-runtime/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/snap/checkbox-iiotg/21/checkbox-runtime/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/snap/checkbox-iiotg/21/checkbox-runtime/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/snap/checkbox-iiotg/21/checkbox-runtime/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks was not provided by any .service files

[Additional information]
CID: 
SKU: 
system-manufacturer: AAEON
system-product-name: UPX-TGL01
bios-version: 5.19
CPU: Intel(R) Celeron(R) 6305E @ 1.80GHz (2x)
GPU: 00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:9a78] (rev 01)
kernel-version: 5.15.0-1010-intel-iotg

[Stage]
Issue reported and logs collected at a later stage

## Attachments
[checkbox-session.tgz](https://api.launchpad.net/devel/bugs/1982291/+attachment/5604207/data)
[snap_list.log](https://api.launchpad.net/devel/bugs/1982291/+attachment/5604208/data)
[acpidump.log](https://api.launchpad.net/devel/bugs/1982291/+attachment/5604209/data)
[sosreport-ubuntu-2022-07-20-rfdjbgz.tar.gz](https://api.launchpad.net/devel/bugs/1982291/+attachment/5604210/data)

Tags:
['checkbox', 'test-case']

**Comment by linjuiche** [comment]
https://github.com/canonical/checkbox/pull/308

**Comment by chihchun** [comment]
This bug is duplicated with #288  and fix in #308

**Comment by pieqq** [comment]
Thanks for pointing out this duplicate! I'll close this issue.
