### ISSUE TITLE
LP1898024: remote get_result stack trace

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#75]
This issue was migrated from https://bugs.launchpad.net/checkbox-ng/+bug/1898024

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2020-10-01 09:50:32	| 6	| High	| False  	|

## Description
```
---------------------------[ Running job 158 / 195 ]----------------------------
--------------------------[ Attach C-States test log ]--------------------------
ID: com.canonical.certification::cpu/cstates_results.log
Category: CPU tests
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/checkbox-cli", line 11, in <module>
    load_entry_point('checkbox-ng==1.10.0.dev0', 'console_scripts', 'checkbox-cli')()
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/checkbox_cli.py", line 123, in main
    subcmd.invoked(ctx)
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/master.py", line 155, in invoked
    self.connect_and_run(ctx.args.host, port)
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/master.py", line 219, in connect_and_run
    keep_running = {
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/master.py", line 435, in resume_interacting
    self.run_jobs()
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/master.py", line 420, in run_jobs
    self._run_jobs(jobs_repr, total_num)
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/master.py", line 607, in _run_jobs
    self.wait_for_job()
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/master.py", line 461, in wait_for_job
    self.finish_job()
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/master.py", line 466, in finish_job
    job_result = self.sa.finish_job(result)
  File "/usr/lib/python3/dist-packages/plainbox/vendor/rpyc/core/netref.py", line 253, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python3/dist-packages/plainbox/vendor/rpyc/core/netref.py", line 76, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/usr/lib/python3/dist-packages/plainbox/vendor/rpyc/core/protocol.py", line 469, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/usr/lib/python3/dist-packages/plainbox/vendor/rpyc/core/async_.py", line 102, in value
    raise self._obj
AttributeError: 'NoneType' object has no attribute 'get_result'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/snap/checkbox-snappy/2037/checkbox-runtime/lib/python3.8/site-packages/plainbox/vendor/rpyc/core/protocol.py", line 320, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/snap/checkbox-snappy/2037/checkbox-runtime/lib/python3.8/site-packages/plainbox/vendor/rpyc/core/protocol.py", line 593, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/snap/checkbox-snappy/2037/checkbox-runtime/lib/python3.8/site-packages/plainbox/impl/session/remote_assistant.py", line 551, in finish_job
    result = self._be.wait().get_result()
AttributeError: 'NoneType' object has no attribute 'get_result'

+ EXITCODE=1
```

**Comment by kissiel** [comment]
It's already fixed.

**Comment by Hook25** [comment]
Reopening this as it is happening again in UC16 edge validation see log: 
```
Traceback (most recent call last):
  File "/usr/bin/checkbox-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/checkbox_cli.py", line 166, in main
    return subcmd.invoked(ctx)
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/controller.py", line 163, in invoked
    return self.connect_and_run(ctx.args.host, port)
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/controller.py", line 291, in connect_and_run
    keep_running = {
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/controller.py", line 368, in new_session
    self.select_jobs(self.jobs)
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/controller.py", line 463, in select_jobs
    self.run_jobs()
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/controller.py", line 569, in run_jobs
    self._run_jobs(jobs_repr, total_num)
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/controller.py", line 811, in _run_jobs
    self.wait_for_job()
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/controller.py", line 612, in wait_for_job
    self.finish_job()
  File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/controller.py", line 617, in finish_job
    job_result = self.sa.finish_job(result)
  File "/usr/lib/python3/dist-packages/plainbox/vendor/rpyc/core/netref.py", line 240, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python3/dist-packages/plainbox/vendor/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/usr/lib/python3/dist-packages/plainbox/vendor/rpyc/core/protocol.py", line 718, in sync_request
    return _async_res.value
  File "/usr/lib/python3/dist-packages/plainbox/vendor/rpyc/core/async_.py", line 108, in value
    raise self._obj
AttributeError: 'NoneType' object has no attribute 'get_result'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/snap/checkbox/4238/checkbox-runtime/lib/python3.5/site-packages/plainbox/vendor/rpyc/core/protocol.py", line 359, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/snap/checkbox/4238/checkbox-runtime/lib/python3.5/site-packages/plainbox/vendor/rpyc/core/protocol.py", line 837, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/snap/checkbox/4238/checkbox-runtime/lib/python3.5/site-packages/plainbox/impl/session/remote_assistant.py", line 599, in finish_job
    result = self._be.wait().get_result()
AttributeError: 'NoneType' object has no attribute 'get_result'
```
