### ISSUE TITLE
checkbox produces stack trace on malformed launcher file

### ISSUE THREAD

**Issue by jocave** [canonical/checkbox#752]
### Bug Description

Given that setup of a launcher file is a "user" action it might be nice to provide a user-friendly response when a badly formatted launcher file is supplied.

### To Reproduce

Run checkbox as below was launcher file as indicated (but without redactions):

```
17:08:42 + checkbox-cli remote 10.102.163.153 checkbox-launcher
17:08:42 Traceback (most recent call last):
17:08:42   File "/usr/bin/checkbox-cli", line 11, in <module>
17:08:42     load_entry_point('checkbox-ng==1.19.0.dev0', 'console_scripts', 'checkbox-cli')()
17:08:42   File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/checkbox_cli.py", line 140, in main
17:08:42     subcmd.invoked(ctx)
17:08:42   File "/usr/lib/python3/dist-packages/checkbox_ng/launcher/master.py", line 140, in invoked
17:08:42     self.launcher.read_string(self._launcher_text)
17:08:42   File "/usr/lib/python3/dist-packages/plainbox/impl/secure/config.py", line 589, in read_string
17:08:42     self._read_commit(parser)
17:08:42   File "/usr/lib/python3/dist-packages/plainbox/impl/secure/config.py", line 658, in _read_commit
17:08:42     value = reader_fn[variable.kind](
17:08:42   File "/usr/lib/python3/dist-packages/plainbox/impl/secure/config.py", line 443, in getlist
17:08:42     return self._get(section, self._convert_to_list, option,  **kwargs)
17:08:42   File "/usr/lib/python3.8/configparser.py", line 803, in _get
17:08:42     return conv(self.get(section, option, **kwargs))
17:08:42   File "/usr/lib/python3/dist-packages/plainbox/impl/secure/config.py", line 450, in _convert_to_list
17:08:42     return shlex.split(value.replace(',', ' '))
17:08:42   File "/usr/lib/python3.8/shlex.py", line 311, in split
17:08:42     return list(lex)
17:08:42   File "/usr/lib/python3.8/shlex.py", line 300, in __next__
17:08:42     token = self.get_token()
17:08:42   File "/usr/lib/python3.8/shlex.py", line 109, in get_token
17:08:42     raw = self.read_token()
17:08:42   File "/usr/lib/python3.8/shlex.py", line 191, in read_token
17:08:42     raise ValueError("No closing quotation")
17:08:42 ValueError: No closing quotation
```

When the following badly formatted launcher was supplied:

```
[launcher]
app_id = com.canonical.qa.jollyville:checkbox
launcher_version = 1
stock_reports = text, submission_files, certification
local_submission = yes
session_desc = redacted

[test plan]
unit = com.canonical.qa.jollyville::jollyville-automated
forced = yes

[test selection]
forced = yes
exclude = com.canonical.certification::image/model-grade
	.*content-plug-connected-provider-ipdt
	com.canonical.certification::ipv6_link_local_address_dsc.*
	com.canonical.qa.jollyville::jollyville-thermal/hwmon0-is-activate
	com.canonical.qa.jollyville::jollyville-ethernet/ping_dsc.* # we can't test QSFP port unless set up another set of jollyville.

[ui]
type = silent
auto_retry = yes
max_attempts = 4
delay_before_retry = 30

[exporter:html]
unit = com.canonical.plainbox::html
options = without-session-desc

[transport:certification]
type = submission-service
secure_id = <redacted>

[report:c3_upload]
transport = certification
exporter = tar

[environment]
<radacted>

[manifest]
com.canonical.certification::has_audio_playback = false
com.canonical.certification::has_audio_capture = false
com.canonical.certification::has_bt_adapter = false
com.canonical.certification::has_ethernet_adapter = true
com.canonical.certification::has_i2c = true
com.canonical.certification::has_card_reader = false
com.canonical.certification::has_thunderbolt3 = false
com.canonical.certification::has_usb_type_c = false
com.canonical.certification::has_usb_storage = false
com.canonical.certification::has_hardware_watchdog = true
com.canonical.certification::has_wlan_adapter = false
com.canonical.certification::has_wwan_module = false
com.canonical.certification::has_tpm2_chip = false

```

### Environment

checkbox-jollyville          0.1dev           5      latest/edge    ce-certification-qa  devmode
checkbox20                   2.7              1299   latest/stable  ce-certification-qa  -

**Comment by Hook25** [comment]
Now fixed, it should now yield a problem and not crash with a stacktrace
