### ISSUE TITLE
LP1916429: disk/storage_device_nvme0n1 failed

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#81]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1916429

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2021-02-22 04:05:39	| 8	| High	| False  	|

## Description
[Summary]
disk/storage_device_nvme0n1 failed
certification_status: unspecified

When the Windows disk does not be clean, this test case will fail.

[I/O log]
Testing disk nvme0n1
identified as a disk...
test will be run on partition /dev/nvme0n1p3
+ mount /dev/nvme0n1p3 /tmp/tmplt1a96u3
Windows is hibernated, refused to mount.
The disk contains an unclean file system (0, 0).
Metadata kept in Windows cache, refused to mount.
Falling back to read-only mount because the NTFS partition is in an
unsafe state. Please resume and shutdown Windows fully (no hibernation
or fast restarting.)
Could not mount read-write, trying read-only
Performed mount /dev/nvme0n1p3 at /tmp/tmplt1a96u3
169262.265625MB of free space avaialble
Forcing memory setting to 8000MB
+ bonnie++ -d /tmp/tmplt1a96u3 -u root -r 8000
Using uid:0, gid:0.
Can't open file ./Bonnie.44911
+ umount /tmp/tmplt1a96u3
Traceback (most recent call last):
  File "/tmp/nest-q45t9ok5.31c87e8f098638c0afa1eb324ec91d6eadc1613fa55a5682526f26226262a817/storage_test.py", line 146, in <module>
    main()
  File "/tmp/nest-q45t9ok5.31c87e8f098638c0afa1eb324ec91d6eadc1613fa55a5682526f26226262a817/storage_test.py", line 142, in main
    disk_test(udev_name)
  File "/tmp/nest-q45t9ok5.31c87e8f098638c0afa1eb324ec91d6eadc1613fa55a5682526f26226262a817/storage_test.py", line 131, in disk_test
    run_bonnie(mount_dir)
  File "/tmp/nest-q45t9ok5.31c87e8f098638c0afa1eb324ec91d6eadc1613fa55a5682526f26226262a817/storage_test.py", line 88, in run_bonnie
    sp.check_call(cmd, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bonnie++ -d /tmp/tmplt1a96u3 -u root -r 8000' returned non-zero exit status 1.

[Reproduce Steps]
1. sudo checkbox-cli run com.canonical.certification::disk/storage_device_nvme0n1

[Results]
failed

## Attachments
No attachments

Tags:
['oem-priority', 'originate-from-1909268', 'somerville']

**Comment by kissiel** [comment]
This is a super corner-case that I don't think we want to cover.
If this becomes a common problem feel free to re-open this issue.
