### ISSUE TITLE
"HTTPConnection.request() got an unexpected keyword argument 'chunked'" exception with Metabox

### ISSUE THREAD

**Issue by alexandredosim** [canonical/checkbox#868]
### Bug Description

Running Metabox I got the following:
```
(metabox) root@Ubuntu-Desktop-22:/home/tester/checkbox/metabox# metabox local-daily-builds-config.py --do-not-dispose --tag basic
20:37:28 | INFO     Including scenario tag(s): basic
Traceback (most recent call last):
  File "/home/tester/checkbox/metabox/metabox/bin/metabox", line 33, in <module>
    sys.exit(load_entry_point('metabox', 'console_scripts', 'metabox')())
  File "/home/tester/checkbox/metabox/metabox/main.py", line 95, in main
    runner.setup()
  File "/home/tester/checkbox/metabox/metabox/core/runner.py", line 222, in setup
    self.machine_provider = LxdMachineProvider(
  File "/home/tester/checkbox/metabox/metabox/core/lxd_provider.py", line 74, in __init__
    self.client = pylxd.Client(timeout=None)
  File "/home/tester/checkbox/metabox/metabox/lib/python3.10/site-packages/pylxd/client.py", line 383, in __init__
    response = self.api.get()
  File "/home/tester/checkbox/metabox/metabox/lib/python3.10/site-packages/pylxd/client.py", line 192, in get
    response = self.session.get(self._api_endpoint, *args, **kwargs)
  File "/home/tester/checkbox/metabox/metabox/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/tester/checkbox/metabox/metabox/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tester/checkbox/metabox/metabox/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/tester/checkbox/metabox/metabox/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/tester/checkbox/metabox/metabox/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/tester/checkbox/metabox/metabox/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: HTTPConnection.request() got an unexpected keyword argument 'chunked'
```

I've found [this issue](https://github.com/docker/docker-py/issues/3113) that indicates it would be a incompatibility with version 2 of urllib3. I've installed the version 1.26.18 and it worked.

### To Reproduce

Copy and paste the [Metabox tutorial](https://github.com/canonical/checkbox/blob/main/metabox/README.md)

### Environment

- Ubuntu Desktop 22.04.4
-VirtualBox

**Comment by Hook25** [comment]
Closing as solved in c40f7942649a4cb5f75ec8a193efa36619b556e8
