### ISSUE TITLE
Auto resume is not working in `edge` channel

### ISSUE THREAD

**Issue by LiaoU3** [canonical/checkbox#935]
### Bug Description
In `stable` and `beta`, checkbox could automatically resume back after a reboot.
But in `edge`, checkbox could not automatcally resume back.

Comparison if could auto resume
| channel | remote | local |
|---------|--------|-------|
| stable (3.0.0) | O      | O     |
| beta  (3.3.0-dev19)  | O      | O    |
| edge  (3.3.0-dev93)  | X      | X     |

>Note: The test cases using `pm_test` like [power-management/poweroff](https://github.com/canonical/checkbox/blob/f31e500b5b83e7bd0875719dd9df5fe6e6c4464f/providers/base/units/power-management/jobs.pxu#L54) or [power-management/reboot](https://github.com/canonical/checkbox/blob/f31e500b5b83e7bd0875719dd9df5fe6e6c4464f/providers/base/units/power-management/jobs.pxu#L77) can not resume back in all channels. This is a know issue, so we are not talking about those cases with `pm_test` (By the way the test cases with `pm_test` is removed from testplans in PR #904). In here we only talk about other regular test cases using `reboot`,  `dbus` etc.

#### snap list
We installed `checkbox` and `checkbox22` with `edge` channel.
```
u@u-UPN-EHL01:~$ snap list 
Name                       Version           Rev    Tracking         Publisher            Notes
bare                       1.0               5      latest/stable    canonical✓           base
checkbox                   3.3.0-dev46       5398   latest/edge      ce-certification-qa  classic
checkbox22                 3.3.0-dev87       764    latest/edge      ce-certification-qa  -
core20                     20231123          2105   latest/stable    canonical✓           base
core22                     20231123          1033   latest/stable    canonical✓           base
firefox                    121.0.1-1         3626   latest/stable/…  mozilla✓             -
gnome-3-38-2004            0+git.efb213a     143    latest/stable/…  canonical✓           -
gnome-42-2204              0+git.ff35a85     141    latest/stable    canonical✓           -
gtk-common-themes          0.1-81-g442e511   1535   latest/stable/…  canonical✓           -
snap-store                 41.3-71-g709398e  959    latest/stable/…  canonical✓           -
snapd                      2.61.1            20671  latest/stable    canonical✓           snapd
snapd-desktop-integration  0.9               83     latest/stable/…  canonical✓           -
```
#### checkbox remote
We run `checkbox.checkbox-cli remote` and select testplan manually then run it. After the DUT reboot, tt reconnects, but it shows me the list of available test plans instead of actually resuming the session.
```
(base) vincent@vincent-XPS-9320:~$ checkbox.checkbox-cli remote 10.102.88.57
WARNING:root:remote is deprecated and will be removed in the next major release of Checkbox. Please use control instead
WARNING:plainbox.providers.v1:$PROVIDERPATH is defined, so following provider sources are ignored ['/home/vincent/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
Connecting to 10.102.88.57:18871. Timeout: 600s
-----------------------------[ Running job 1 / 5 ]------------------------------
--------------------------------[ Warm reboot ]---------------------------------
ID: com.canonical.certification::power-management/warm-reboot
Category: Power Management tests
--------------------------------------------------------------------------------
Connection lost!
connection closed by peer
Reconnecting ...
Reconnected (took: 55s) # Checkbox shows "Select Test Plan" screen instead of resuming the session
(base) vincent@vincent-XPS-9320:~$ 
```

### To Reproduce

1. Install Stock Ubuntu on the DUT and your computer
2. Install checkbox on the DUT and your computer
   1. sudo snap install checkbox --edge --classic
   2. sudo nap install checkbox22 --edge
3. Run checkbox remote on your computer
   1. checkbox.checkbox-cli remote {DUT IP}
   2. Select [Automated power tests](https://github.com/canonical/checkbox/blob/228b716bba2ec511f09ee36bf87aa969d348df8b/providers/base/units/power-management/test-plan.pxu#L96C5-L96C20)

or

3. Local run checkbox on DUT
   1. checkbox.checkbox-cli
   2. Select [Automated power tests](https://github.com/canonical/checkbox/blob/228b716bba2ec511f09ee36bf87aa969d348df8b/providers/base/units/power-management/test-plan.pxu#L96C5-L96C20)

### Environment

 - OS: Ubuntu 22.04 Desktop
 - Kernel: 5.15.0-1046-intel-iotg
 - Checkbox Type: Snap
 - Checkbox version: 
    - checkbox: 3.3.0-dev46
    - checkbox22: 3.3.0-dev87

**Comment by pieqq** [comment]
What happens if you use a launcher to run this test plan completely automatically?

```
[launcher]
launcher_version = 1
stock_reports = text
[test plan]
unit = com.canonical.certification::power-automated
forced = yes
[test selection]
forced = yes
[ui]
type = silent
```

**Comment by LiaoU3** [comment]
@pieqq If I run with the launcher you provided, it could resume back automatically.

**Comment by LiaoU3** [comment]
By the way, I also try with stable and beta version of `checkbox` and `checkbox22`, I didn't observed this issue in it. They could resume back automatically.

**Comment by zongminl** [comment]
This is going to be a blocker for ODM program customer, so the next release of checkbox to stable channel needs to be blocked with it

**Comment by pieqq** [comment]
The problem here is that although using a launcher is a good workaround, the customer still needs access to the Manifest Entry UI when running Checkbox for the first time in order to setup the DUT. (different DUTs would have different Manifest entries, so we cannot provide a generic launcher)

**Comment by Hook25** [comment]
@LiaoU3 can you check if the new resume menu solves the issue? You should now be able (in edge) to resume any session via the menu

**Comment by LiaoU3** [comment]
@Hook25
# Snap version
```
checkbox                   4.0.0-dev119                5961   latest/edge      ce-certification-qa  classic
checkbox22                 4.0.0-dev119                817    latest/edge      ce-certification-qa  -
```
# In remote run
We could resume it back menually. But is'nt it should resume itself back automatically?
![Screenshot from 2024-02-23 10-55-31](https://github.com/canonical/checkbox/assets/58060146/dcf94dc6-b77e-4eb8-b679-9fce6fcf060e)

# In local run 
This one also could be resumed back manually but not automatically.
![Screenshot from 2024-02-23 11-02-07](https://github.com/canonical/checkbox/assets/58060146/892834cb-9c9d-4032-8fc1-cbc60365a7b8)

# Conclusion
Even though we could resume it back manually now, we are still not able to do it automatically. So in my opinion, I think this is still not fixed.

**Comment by LiaoU3** [comment]
Yes, exactly.

**Comment by Hook25** [comment]
Ok this was auto closed but I want you to double check if the new behaviour is workable for you. Please do try the version currently  in source (will be in edge by tomorrow) and let me know if it feets your needs or we need to tune it a bit more

**Comment by LiaoU3** [comment]
# Environment
 - Versio: 4.0.0-dev133 
 - Hardware: ARK 3534D#2 ([202401-33386](https://certification.canonical.com/hardware/202401-33386/))

# Remote run - Pass
It succefully resumes back.
```
(base) vincent@vincent-XPS-9320:~$ checkbox.checkbox-cli remote 10.102.88.9
WARNING:root:remote is deprecated and will be removed in the next major release of Checkbox. Please use control instead
WARNING:plainbox.providers.v1:$PROVIDERPATH is defined, so following provider sources are ignored ['/home/vincent/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
Connecting to 10.102.88.9:18871. Timeout: 600s
-----------------------------[ Running job 1 / 5 ]------------------------------
--------------------------------[ Warm reboot ]---------------------------------
ID: com.canonical.certification::power-management/warm-reboot
Category: Power Management tests
--------------------------------------------------------------------------------
Connection lost!
connection closed by peer
Reconnecting ...
Reconnected (took: 28s)
-----------------------------[ Running job 2 / 5 ]------------------------------
-----------------------[ Post warm reboot service check ]-----------------------
ID: com.canonical.certification::power-management/post-warm-reboot
Category: Power Management tests
--------------------------------------------------------------------------------
Found 0 failed units
--------------------------------------------------------------------------------
Outcome: job passed
-----------------------------[ Running job 3 / 5 ]------------------------------
-----------------------[ Creates resource info for RTC ]------------------------
ID: com.canonical.certification::rtc
Category: Gathers information about the DUT
--------------------------------------------------------------------------------
state: supported
--------------------------------------------------------------------------------
Outcome: job passed
-----------------------------[ Running job 4 / 5 ]------------------------------
--------------------------------[ Cold reboot ]---------------------------------
ID: com.canonical.certification::power-management/cold-reboot
Category: Power Management tests
--------------------------------------------------------------------------------
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup using /dev/rtc0 at Mon Mar  4 02:50:40 2024
rtcwake: assuming RTC uses UTC ...
alarm: on  Mon Mar  4 02:50:40 2024
Connection lost!
connection closed by peer
Reconnecting ...
Reconnected (took: 134s)
-----------------------------[ Running job 5 / 5 ]------------------------------
-----------------------[ Post cold reboot service check ]-----------------------
ID: com.canonical.certification::power-management/post-cold-reboot
Category: Power Management tests
--------------------------------------------------------------------------------
Found 0 failed units
--------------------------------------------------------------------------------
Outcome: job passed
==================================[ Results ]===================================
32.0kB [00:00, 235kB/s, file=python://stdout]                                                                                                                                
  job passed   : Warm reboot
  job passed   : Post warm reboot service check
  job passed   : Creates resource info for RTC
  job passed   : Cold reboot
  job passed   : Post cold reboot service check
704kB [00:00, 1.86MB/s, file=/home/vincent/.local/share/checkbox-ng/submission_2024-03-04T02.51.25.818449.html]                                                              
file:///home/vincent/.local/share/checkbox-ng/submission_2024-03-04T02.51.25.818449.html
32.0kB [00:00, 1.61MB/s, file=/home/vincent/.local/share/checkbox-ng/submission_2024-03-04T02.51.25.818449.junit.xml]                                                        
file:///home/vincent/.local/share/checkbox-ng/submission_2024-03-04T02.51.25.818449.junit.xml
176kB [00:00, 1.66MB/s, file=/home/vincent/.local/share/checkbox-ng/submission_2024-03-04T02.51.25.818449.tar.xz]                                                            
file:///home/vincent/.local/share/checkbox-ng/submission_2024-03-04T02.51.25.818449.tar.xz
Do you want to submit 'upload to certification' report?
  y => yes
  n => no
[yn]: 
```
# Local run
It is still not able to resume back automatically. I have to manually resume the session.
Same behavior as the output in the [comment](https://github.com/canonical/checkbox/issues/935#issuecomment-1960670273).
# Conclusion
It can now resume sessions automatically in remote run. Whereas, it is still not able to resume sessions back automatically in local run. What I expect is it can resume sessions back automatically in both remote or local run.

**Comment by Hook25** [comment]
Second time is the charm, please do check tomorrow if it now works using local as well.

**Comment by LiaoU3** [comment]
I think I found a weird bug that if I want to run checkbox.checkbox-cli again after `Auto power test` testplan run. It will get error. So I am not able to check if this issue is fixed.
```
u@u:~$ checkbox.checkbox-cli 
$PROVIDERPATH is defined, so following provider sources are ignored ['/home/u/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
WARNING:plainbox.secure.providers.v1:Skipped file: /snap/checkbox22/current/providers/checkbox-provider-base/units/stress/suspend_cycles_reboot.md
[sudo] password for u: 
Removed /etc/systemd/system/multi-user.target.wants/plainbox-autostart.service.
Failed to disable unit: Unit file plainbox-autostart.service does not exist.
rm: cannot remove '/etc/systemd/system/plainbox-autostart.service': No such file or directory
Reports will be saved to: /home/u/.local/share/checkbox-ng
==============[ Running job 1 / 1. Estimated time left: 0:00:01 ]===============
-----------------------[ Post cold reboot service check ]-----------------------
ID: com.canonical.certification::power-management/post-cold-reboot
Category: com.canonical.plainbox::power-management
... 8< -------------------------------------------------------------------------
Found 1 failed units

Failed units:
  UNIT                       LOAD   ACTIVE SUB    DESCRIPTION
● plainbox-autostart.service loaded failed failed Plainbox Resume Wrapper

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
1 loaded units listed.
------------------------------------------------------------------------- >8 ---
Outcome: job failed
u@u:~$ checkbox.checkbox-cli 
$PROVIDERPATH is defined, so following provider sources are ignored ['/home/u/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
WARNING:plainbox.secure.providers.v1:Skipped file: /snap/checkbox22/current/providers/checkbox-provider-base/units/stress/suspend_cycles_reboot.md
Failed to disable unit: Unit file plainbox-autostart.service does not exist.
rm: cannot remove '/etc/systemd/system/plainbox-autostart.service': No such file or directory
Failed to disable unit: Unit file plainbox-autostart.service does not exist.
rm: cannot remove '/etc/systemd/system/plainbox-autostart.service': No such file or directory
Traceback (most recent call last):
  File "/snap/checkbox22/current/bin/checkbox-cli", line 8, in <module>
    sys.exit(main())
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/checkbox_cli.py", line 163, in main
    return subcmd.invoked(ctx)
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/subcommands.py", line 254, in invoked
    if not self._auto_resume_session(self.resume_candidates):
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/subcommands.py", line 421, in _auto_resume_session
    self._resume_session(last_session.id, None)
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/subcommands.py", line 531, in _resume_session
    outcome = self._get_autoresume_outcome_last_job(metadata)
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/subcommands.py", line 512, in _get_autoresume_outcome_last_job
    if "noreturn" in job_state.job.flags:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by LiaoU3** [comment]
Ok I think I know how to `avoid` this bug. We just have to remove all stuff under `/var/tmp/checkbox-ng/sessions/*`, then we are able to run `checkbox.checkbox-cli` without any error.
And after I tried this, it looks like it is still not fixed in local run.

And it also looks like remote run is broken too.
```
(base) vincent@vincent-XPS-9320:~$ checkbox.checkbox-cli remote 10.102.89.30
WARNING:root:remote is deprecated and will be removed in the next major release of Checkbox. Please use control instead
WARNING:plainbox.providers.v1:$PROVIDERPATH is defined, so following provider sources are ignored ['/home/vincent/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
Connecting to 10.102.89.30:18871. Timeout: 600s
Traceback (most recent call last):
  File "/snap/checkbox22/current/bin/checkbox-cli", line 8, in <module>
    sys.exit(main())
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/checkbox_cli.py", line 163, in main
    return subcmd.invoked(ctx)
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/controller.py", line 175, in invoked
    return self.connect_and_run(ctx.args.host, port)
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/controller.py", line 303, in connect_and_run
    keep_running = {
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/controller.py", line 455, in resume_or_start_new_session
    if self.should_start_via_autoresume():
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/controller.py", line 400, in should_start_via_autoresume
    last_abandoned_session = next(self.sa.get_resumable_sessions())
  File "/snap/checkbox22/current/lib/python3.10/site-packages/plainbox/vendor/rpyc/core/netref.py", line 261, in method
    return syncreq(_self, consts.HANDLE_CALLATTR, name, args, kwargs)
  File "/snap/checkbox22/current/lib/python3.10/site-packages/plainbox/vendor/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/snap/checkbox22/current/lib/python3.10/site-packages/plainbox/vendor/rpyc/core/protocol.py", line 718, in sync_request
    return _async_res.value
  File "/snap/checkbox22/current/lib/python3.10/site-packages/plainbox/vendor/rpyc/core/async_.py", line 108, in value
    raise self._obj
plainbox.vendor.rpyc.core.vinegar/plainbox.impl.developer._get_exception_class.<locals>.Derived: ("<class 'plainbox.impl.session.assistant.SessionAssistant'>", 'get_resumable_sessions', (('select_test_plan', 'to save test plan selection'), ('use_alternate_configuration', 'use an alternate configuration system')))

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/snap/checkbox22/current/lib/python3.10/site-packages/plainbox/vendor/rpyc/core/protocol.py", line 359, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/snap/checkbox22/current/lib/python3.10/site-packages/plainbox/vendor/rpyc/core/protocol.py", line 863, in _handle_callattr
    return self._handle_call(obj, args, kwargs)
  File "/snap/checkbox22/current/lib/python3.10/site-packages/plainbox/vendor/rpyc/core/protocol.py", line 837, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/snap/checkbox22/current/lib/python3.10/site-packages/plainbox/impl/session/assistant.py", line 629, in get_resumable_sessions
    UsageExpectation.of(self).enforce()
  File "/snap/checkbox22/current/lib/python3.10/site-packages/plainbox/impl/developer.py", line 222, in enforce
    raise UnexpectedMethodCall(self.cls, fn_name, allowed_pairs)
plainbox.impl.developer.UnexpectedMethodCall: 
Uh, oh...

You are not expected to call SessionAssistant.get_resumable_sessions() at this time.

If you see this message then there is a bug somewhere in your code. We are
sorry for this. Perhaps the documentation is flawed, incomplete or confusing.
Please reach out to us if  this happens more often than you'd like.

The set of allowed calls, at this time, is:

 - call SessionAssistant.select_test_plan() to to save test plan selection.
 - call SessionAssistant.use_alternate_configuration() to use an alternate configuration system.

Refer to the documentation of SessionAssistant for details.
    TIP: python -m pydoc plainbox.impl.session.assistant.SessionAssistant
```

**Comment by LiaoU3** [comment]
# Environment
 - snap version: 4.0.0-dev139
 - Hardware: ARK 3534D (202401-33387)

# Remote - Pass
Remote run function well now.
```console
(base) vincent@vincent-XPS-9320:~$ checkbox.checkbox-cli remote 10.102.89.30
WARNING:root:remote is deprecated and will be removed in the next major release of Checkbox. Please use control instead
WARNING:plainbox.providers.v1:$PROVIDERPATH is defined, so following provider sources are ignored ['/home/vincent/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
Connecting to 10.102.89.30:18871. Timeout: 600s
-----------------------------[ Running job 1 / 5 ]------------------------------
--------------------------------[ Warm reboot ]---------------------------------
ID: com.canonical.certification::power-management/warm-reboot
Category: Power Management tests
--------------------------------------------------------------------------------
Connection lost!
connection closed by peer
Reconnecting ...
Reconnected (took: 31s)
-----------------------------[ Running job 2 / 5 ]------------------------------
-----------------------[ Post warm reboot service check ]-----------------------
ID: com.canonical.certification::power-management/post-warm-reboot
Category: Power Management tests
--------------------------------------------------------------------------------
Found 0 failed units
--------------------------------------------------------------------------------
Outcome: job passed
-----------------------------[ Running job 3 / 5 ]------------------------------
-----------------------[ Creates resource info for RTC ]------------------------
ID: com.canonical.certification::rtc
Category: Gathers information about the DUT
--------------------------------------------------------------------------------
state: supported
--------------------------------------------------------------------------------
Outcome: job passed
-----------------------------[ Running job 4 / 5 ]------------------------------
--------------------------------[ Cold reboot ]---------------------------------
ID: com.canonical.certification::power-management/cold-reboot
Category: Power Management tests
--------------------------------------------------------------------------------
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup using /dev/rtc0 at Thu Mar  7 08:59:24 2024
rtcwake: assuming RTC uses UTC ...
alarm: on  Thu Mar  7 08:59:24 2024
Connection lost!
connection closed by peer
Reconnecting ...
Reconnected (took: 134s)
-----------------------------[ Running job 5 / 5 ]------------------------------
-----------------------[ Post cold reboot service check ]-----------------------
ID: com.canonical.certification::power-management/post-cold-reboot
Category: Power Management tests
--------------------------------------------------------------------------------
Found 0 failed units
--------------------------------------------------------------------------------
Outcome: job passed
==================================[ Results ]===================================
32.0kB [00:00, 1.95MB/s, file=python://stdout]                                                                                                                                                
  job passed   : Warm reboot
  job passed   : Post warm reboot service check
  job passed   : Creates resource info for RTC
  job passed   : Cold reboot
  job passed   : Post cold reboot service check
704kB [00:00, 1.73MB/s, file=/home/vincent/.local/share/checkbox-ng/submission_2024-03-07T09.00.08.184971.html]                                                                               
file:///home/vincent/.local/share/checkbox-ng/submission_2024-03-07T09.00.08.184971.html
32.0kB [00:00, 1.76MB/s, file=/home/vincent/.local/share/checkbox-ng/submission_2024-03-07T09.00.08.184971.junit.xml]                                                                         
file:///home/vincent/.local/share/checkbox-ng/submission_2024-03-07T09.00.08.184971.junit.xml
176kB [00:00, 1.59MB/s, file=/home/vincent/.local/share/checkbox-ng/submission_2024-03-07T09.00.08.184971.tar.xz]                                                                             
file:///home/vincent/.local/share/checkbox-ng/submission_2024-03-07T09.00.08.184971.tar.xz
Do you want to submit 'upload to certification' report?
  y => yes
  n => no
[yn]: 
```

**Comment by LiaoU3** [comment]
I think I know the reason why local run is failed. It may be the root issue in local run. Following the below process could run the  cold reboot and warm reboot successfully. However, there is another issue that after the DUT poweroff, it never power on again.
Reproduce process
1. sudo su
2. checkbox.checkbox-cli
3. Select Automated powet test
4. Wait for it to warm reboot
5. Warm reboot successfully
6. Wait for it to cold reboot
7. power off successfully
8. Never power on

Hence, I suggest that maybe we need another issue to trask this bug.

**Comment by Hook25** [comment]
Yes I agree, lets close this one and open another one about this specific issue. As communicated in DM, I think we are ready to release the current version to beta!

**Comment by LiaoU3** [comment]
Thank you for your help!

**Comment by LiaoU3** [comment]
I've opened Issue #1045 to track the local root user bug.
