### ISSUE TITLE
LP1969173: graphics jobs relying a $XDG_SESSION_TYPE do not work after reboot

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#95]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1969173

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-04-15 02:44:27	| 6	| High	| False  	|

## Description
plainbox-provider-checkbox 0.64.0~rc1~ppa~ubuntu22.04.1

CID: 202103-28858
Image: 22.04 beta
desktop env: Wayland
GNOME 42

In the test plan I'm running (22.04 manual), the following job is executed after a reboot:

-------------[ Running job 5 / 128. Estimated time left: unknown ]--------------
[ Test rotation for NVIDIA Corporation GA104GLM [RTX A5000 Mobile] after suspend ]
ID: com.canonical.certification::suspend/2_rotation_after_suspend_GA104GLM__RTX_A5000_Mobile__graphics
Category: com.canonical.plainbox::suspend
PURPOSE:
    This test will test display rotation on the NVIDIA Corporation GA104GLM [RTX A5000 Mobile] graphics card after suspend
STEPS:
    1. Click "Test" to test display rotation. The display will be rotated every 4 seconds.
    2. Check if all rotations (normal right inverted left) took place without permanent screen corruption
VERIFICATION:
    Did the display rotation take place without permanent screen corruption after suspend?
Pick an action
    => press ENTER to continue
  c => add a comment
  s => skip this job
  q => save the session and quit
[csq]:
... 8< -------------------------------------------------------------------------
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  22
  Current serial number in output stream:  23
Using output: XWAYLAND0
setting rotation to right
Traceback (most recent call last):
  File "/tmp/nest-fuinyul6.a298bc084873bc0897421dc8e0a5d237a284d6af29c2fdc62079ab2db36002ac/rotation_test.py", line 53, in <module>
    exit(main())
  File "/tmp/nest-fuinyul6.a298bc084873bc0897421dc8e0a5d237a284d6af29c2fdc62079ab2db36002ac/rotation_test.py", line 47, in main
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['xrandr', '--output', 'XWAYLAND0', '--rotation', 'right']' returned non-zero exit status 1.
------------------------------------------------------------------------- >8 ---

As explained in lp:1968983, after reboot, a new terminal is opened and the Checkbox session is resumed. However, in this terminal, $XDG_SESSION_TYPE is not set, which causes the rotation_test.py script to default to Xorg, and it fails.

Fortunately, the job is a user-verify one, so user can still run the tests manually and set the job output accordingly.

The same happens with:

-------------[ Running job 7 / 128. Estimated time left: unknown ]--------------
[ suspend/2_cycle_resolutions_after_suspend_GA104GLM__RTX_A5000_Mobile__graphics ]
ID: com.canonical.certification::suspend/2_cycle_resolutions_after_suspend_GA104GLM__RTX_A5000_Mobile__graphics
Category: com.canonical.plainbox::suspend
PURPOSE:
    This test will cycle through the detected display modes
STEPS:
    1. Click "Test" and the display will cycle trough the display modes
VERIFICATION:
    Did your display look fine in the detected mode?
Pick an action
    => press ENTER to continue
  c => add a comment
  s => skip this job
  q => save the session and quit
[csq]: 
... 8< -------------------------------------------------------------------------
Set mode 3840x2160 for output XWAYLAND0
** Message: 10:48:39.086: Unable to use GNOME Shell's builtin screenshot interface, resorting to fallback X11.
Set mode 2048x1536 for output XWAYLAND0
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  22
  Current serial number in output stream:  23
Failed to set mode 2048x1536 for output XWAYLAND0
Set mode 1280x1024 for output XWAYLAND0
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  22
  Current serial number in output stream:  23
Failed to set mode 1280x1024 for output XWAYLAND0
Set mode 2560x1600 for output XWAYLAND0
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  22
  Current serial number in output stream:  23
Failed to set mode 2560x1600 for output XWAYLAND0
Set mode 1368x768 for output XWAYLAND0
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  22
  Current serial number in output stream:  23
Failed to set mode 1368x768 for output XWAYLAND0
------------------------------------------------------------------------- >8 -

## Attachments
No attachments

Tags:
['jammy-test']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~sylvain-pineau wrote on 2022-04-15 08:09:32:
My recommendation is to run checkbox sessions over remote. $XDG_SESSION_TYPE will correctly be set.
