### ISSUE TITLE
"roundtrip-qrcode" job doesn't work on Core when using remote

### ISSUE THREAD

**Issue by p-gentili** [canonical/checkbox#984]
### Bug Description

The roundtrip-qrcode is failing with Permission Error when running via remote on Ubuntu Core.

When running locally the output is:
```
==============[ Running job 9 / 10. Estimated time left: 0:00:10 ]==============
---[ Test video output and camera vchiq by displaying and reading a qrcode ]----
ID: com.canonical.certification::camera/roundtrip-qrcode_vchiq
Category: com.canonical.plainbox::camera
... 8< -------------------------------------------------------------------------
Testing device name: vchiq

Input string: MaTPfpJcEJ
Generating QR code...
Displaying on screen
Capture image of screen
Image /var/tmp/checkbox-ng/sessions/session_title-2024-02-09T13.33.40.session/session-share/vchiq_qrcapture.png captured
Decoding image file
ERROR: no qrcodes decoded
```

With remote instead is:
```
      Testing device name: vchiq

Input string: eTyITNHlwI
Generating QR code...
Displaying on screen
Traceback (most recent call last):
  File "/tmp/nest-_z6e49ev.b8c0511a367289f6ccf7385b1fd7df4a1c2f895565de63831cc8e5fc09e7ee57/roundtrip_qr.py", line 121, in <module>
    main()
  File "/tmp/nest-_z6e49ev.b8c0511a367289f6ccf7385b1fd7df4a1c2f895565de63831cc8e5fc09e7ee57/roundtrip_qr.py", line 102, in main
    display_code(qr)
  File "/tmp/nest-_z6e49ev.b8c0511a367289f6ccf7385b1fd7df4a1c2f895565de63831cc8e5fc09e7ee57/roundtrip_qr.py", line 65, in display_code
    with open('/dev/tty0', 'wb+', buffering=0) as term:
PermissionError: [Errno 1] Operation not permitted: '/dev/tty0'
```

### To Reproduce

1. Access a DUT with Ubuntu Core (22) installed
2. Run the `com.canonical.certification::camera-automated` testplan via Checkbox remote

### Environment

- OS: UC 22
- Checkbox Version: 3.3.0-dev19 (controller),  uc22/stable (DUT)
- DUT: RPi 3B Plus, RPi 4B 8GB

**Comment by p-gentili** [comment]
Can confirm this is not happening anymore. 
```
Testing device name: vchiq

Input string: sZbBYLrIPz
Generating QR code...
Displaying on screen
Capture image of screen
Image /var/tmp/checkbox-ng/sessions/session_title-2025-11-24T10.58.57.session/session-share/vchiq_qrcapture.png captured
Decoding image file
Decoded data: sZbBYLrIPz
PASS: decoded data and input match
```

this is on a rpi4b4g running UC22.
internal reference: https://certification.canonical.com/hardware/202004-27866/submission/460344
