### ISSUE TITLE
beacon eddystone test crashes with a traceback

### ISSUE THREAD

**Issue by kissiel** [canonical/checkbox#986]
### Bug Description

On some systems, randomly (but not infrequently) we get the following traceback when running the eddystone test:
```
Traceback (most recent call last):
  File "/snap/checkbox-iiotg/46/checkbox-runtime/bin/checkbox-support-eddystone_scanner", line 8, in <module>
    sys.exit(main())
  File "/snap/checkbox-iiotg/46/checkbox-runtime/lib/python3.10/site-packages/checkbox_support/scripts/eddystone_scanner.py", line 70, in main
    init_bluetooth()
  File "/snap/checkbox-iiotg/46/checkbox-runtime/lib/python3.10/site-packages/checkbox_support/scripts/eddystone_scanner.py", line 35, in init_bluetooth
    btctl.writeline('scan on')
  File "/snap/checkbox-iiotg/46/checkbox-runtime/lib/python3.10/site-packages/checkbox_support/interactive_cmd.py", line 84, in writeline
    self._proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

### To Reproduce

`checkbox-cli run com.canonical.certification::bluetooth4/beacon_eddystone_url_hci0.com.canonical.certification::bluetooth4/beacon_eddystone_url_hci0`

### Environment

checkbox snap, uc22 

### Relevant log output

```shell
Traceback (most recent call last):
  File "/snap/checkbox-iiotg/46/checkbox-runtime/bin/checkbox-support-eddystone_scanner", line 8, in <module>
    sys.exit(main())
  File "/snap/checkbox-iiotg/46/checkbox-runtime/lib/python3.10/site-packages/checkbox_support/scripts/eddystone_scanner.py", line 70, in main
    init_bluetooth()
  File "/snap/checkbox-iiotg/46/checkbox-runtime/lib/python3.10/site-packages/checkbox_support/scripts/eddystone_scanner.py", line 35, in init_bluetooth
    btctl.writeline('scan on')
  File "/snap/checkbox-iiotg/46/checkbox-runtime/lib/python3.10/site-packages/checkbox_support/interactive_cmd.py", line 84, in writeline
    self._proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```
```


### Additional context

_No response_

**Comment by yphus** [comment]
is it the same issue I reported in lp in 2019? https://bugs.launchpad.net/checkbox-support/+bug/1811675

**Comment by kissiel** [comment]
Ha! Indeed looks like it. I'm also shocked that I worked on it, and totally purged it from my memory.
I guess I might want to take another look.
